var TesseractCore=(()=>{var _scriptName=typeof document!="undefined"?document.currentScript?.src:undefined;return async function(moduleArg={}){var moduleRtn;var e=moduleArg,aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da="./this.program",ea=(a,b)=>{throw b;};"undefined"!=typeof __filename?_scriptName=__filename:ba&&(_scriptName=self.location.href);var fa="",ha,ia;
if(ca){var fs=require("fs");fa=__dirname+"/";ia=a=>{a=ja(a)?new URL(a):a;return fs.readFileSync(a)};ha=async a=>{a=ja(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);ea=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{fa=(new URL(".",_scriptName)).href}catch{}ba&&(ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ha=async a=>
{if(ja(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ka=console.log.bind(console),la=console.error.bind(console),ma,na=!1,ja=a=>a.startsWith("file://"),oa,pa,qa,g,l,ra,n,p,sa,ta,ua,va=!1;
function wa(){var a=qa.buffer;g=new Int8Array(a);ra=new Int16Array(a);l=new Uint8Array(a);new Uint16Array(a);n=new Int32Array(a);p=new Uint32Array(a);sa=new Float32Array(a);ta=new Float64Array(a);ua=new BigInt64Array(a);new BigUint64Array(a)}function r(a){e.onAbort?.(a);a="Aborted("+a+")";la(a);na=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");pa?.(a);throw a;}var xa;
async function ya(a){if(!ma)try{var b=await ha(a);return new Uint8Array(b)}catch{}if(a==xa&&ma)a=new Uint8Array(ma);else if(ia)a=ia(a);else throw"both async and sync fetching of the wasm failed";return a}async function za(a,b){try{var c=await ya(a);return await WebAssembly.instantiate(c,b)}catch(d){la(`failed to asynchronously prepare wasm: ${d}`),r(d)}}
async function Aa(a){var b=xa;if(!ma&&!ja(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){la(`wasm streaming compile failed: ${d}`),la("falling back to ArrayBuffer instantiation")}return za(b,a)}class Ba{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var Ca=a=>{for(;0<a.length;)a.shift()(e)},Da=[],Ea=[],Fa=()=>{var a=e.preRun.shift();Ea.push(a)};
function Ga(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return g[a];case "i8":return g[a];case "i16":return ra[a>>1];case "i32":return n[a>>2];case "i64":return ua[a>>3];case "float":return sa[a>>2];case "double":return ta[a>>3];case "*":return p[a>>2];default:r(`invalid type for getValue: ${b}`)}}var Ha=!0;
function Ia(a,b,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":g[a]=b;break;case "i8":g[a]=b;break;case "i16":ra[a>>1]=b;break;case "i32":n[a>>2]=b;break;case "i64":ua[a>>3]=BigInt(b);break;case "float":sa[a>>2]=b;break;case "double":ta[a>>3]=b;break;case "*":p[a>>2]=b;break;default:r(`invalid type for setValue: ${c}`)}}
var Ja="undefined"!=typeof TextDecoder?new TextDecoder:void 0,v=(a,b=0)=>{var c=b;for(var d=c+void 0;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ja)return Ja.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|h);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|k:(f&7)<<18|h<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d},
w=a=>a?v(l,a):"";class Ka{constructor(a){this.zf=a-24}dg(a,b){p[this.zf+16>>2]=0;p[this.zf+4>>2]=a;p[this.zf+8>>2]=b}}
var La=0,Ma=0,Qa=()=>{var a=n[+Pa>>2];Pa+=4;return a},Ra=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Sa=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Ra(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ta=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";
b&&=b.slice(0,-1);return a+b},Ua=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Va=(a,b)=>Sa(a+"/"+b),Wa=()=>{if(ca){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Ya=a=>{(Ya=Wa())(a)},Za=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:x.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Ra(b.split("/").filter(f=>!!f),!c).join("/");return(c?"/":"")+b||"."},$a=
(a,b)=>{function c(k){for(var m=0;m<k.length&&""===k[m];m++);for(var u=k.length-1;0<=u&&""===k[u];u--);return m>u?[]:k.slice(m,u-m+1)}a=Za(a).slice(1);b=Za(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),f=d,h=0;h<d;h++)if(a[h]!==b[h]){f=h;break}d=[];for(h=f;h<a.length;h++)d.push("..");d=d.concat(b.slice(f));return d.join("/")},ab=[],bb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},
cb=(a,b,c,d)=>{if(!(0<d))return 0;var f=c;d=c+d-1;for(var h=0;h<a.length;++h){var k=a.codePointAt(h);if(127>=k){if(c>=d)break;b[c++]=k}else if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6;b[c++]=128|k&63}else if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12;b[c++]=128|k>>6&63;b[c++]=128|k&63}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63;b[c++]=128|k>>6&63;b[c++]=128|k&63;h++}}b[c]=0;return c-f},db=(a,b)=>{var c=Array(bb(a)+1);a=cb(a,c,0,c.length);b&&(c.length=a);return c},eb=[];
function fb(a,b){eb[a]={input:[],output:[],Sf:b};gb(a,hb)}
var hb={open(a){var b=eb[a.node.rdev];if(!b)throw new x.Af(43);a.tty=b;a.seekable=!1},close(a){a.tty.Sf.fsync(a.tty)},fsync(a){a.tty.Sf.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Sf.Bg)throw new x.Af(60);for(var f=0,h=0;h<d;h++){try{var k=a.tty.Sf.Bg(a.tty)}catch(m){throw new x.Af(29);}if(void 0===k&&0===f)throw new x.Af(6);if(null===k||void 0===k)break;f++;b[c+h]=k}f&&(a.node.atime=Date.now());return f},write(a,b,c,d){if(!a.tty||!a.tty.Sf.sg)throw new x.Af(60);try{for(var f=0;f<d;f++)a.tty.Sf.sg(a.tty,
b[c+f])}catch(h){throw new x.Af(29);}d&&(a.node.mtime=a.node.ctime=Date.now());return f}},ib={Bg(){a:{if(!ab.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(f){if(f.toString().includes("EOF"))c=0;else throw f;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}ab=db(a,!0)}a=ab.shift()}return a},sg(a,b){null===b||10===
b?(ka(v(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(ka(v(a.output)),a.output=[])},lh(){return{yh:25856,Ah:5,xh:191,zh:35387,wh:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},mh(){return 0},nh(){return[24,80]}},jb={sg(a,b){null===b||10===b?(la(v(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(la(v(a.output)),a.output=[])}},lb=a=>{a=65536*Math.ceil(a/65536);var b=kb(65536,a);b&&l.fill(0,b,b+a);return b},
y={Pf:null,Gf(){return y.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||x.isFIFO(c))throw new x.Af(63);y.Pf||(y.Pf={dir:{node:{Lf:y.Bf.Lf,Nf:y.Bf.Nf,lookup:y.Bf.lookup,Rf:y.Bf.Rf,rename:y.Bf.rename,unlink:y.Bf.unlink,rmdir:y.Bf.rmdir,readdir:y.Bf.readdir,symlink:y.Bf.symlink},stream:{Jf:y.Cf.Jf}},file:{node:{Lf:y.Bf.Lf,Nf:y.Bf.Nf},stream:{Jf:y.Cf.Jf,read:y.Cf.read,write:y.Cf.write,Yf:y.Cf.Yf,ag:y.Cf.ag}},link:{node:{Lf:y.Bf.Lf,Nf:y.Bf.Nf,readlink:y.Bf.readlink},stream:{}},
xg:{node:{Lf:y.Bf.Lf,Nf:y.Bf.Nf},stream:x.Lg}});c=x.createNode(a,b,c,d);z(c.mode)?(c.Bf=y.Pf.dir.node,c.Cf=y.Pf.dir.stream,c.Df={}):x.isFile(c.mode)?(c.Bf=y.Pf.file.node,c.Cf=y.Pf.file.stream,c.If=0,c.Df=null):40960===(c.mode&61440)?(c.Bf=y.Pf.link.node,c.Cf=y.Pf.link.stream):8192===(c.mode&61440)&&(c.Bf=y.Pf.xg.node,c.Cf=y.Pf.xg.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.Df[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},Jh(a){return a.Df?a.Df.subarray?a.Df.subarray(0,a.If):new Uint8Array(a.Df):
new Uint8Array(0)},Bf:{Lf(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;z(a.mode)?b.size=4096:x.isFile(a.mode)?b.size=a.If:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},Nf(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.If!=b&&(0==b?
(a.Df=null,a.If=0):(c=a.Df,a.Df=new Uint8Array(b),c&&a.Df.set(c.subarray(0,Math.min(b,a.If))),a.If=b)))},lookup(){y.hg||(y.hg=new x.Af(44),y.hg.stack="<generic error, no stack>");throw y.hg;},Rf(a,b,c,d){return y.createNode(a,b,c,d)},rename(a,b,c){try{var d=mb(b,c)}catch(h){}if(d){if(z(a.mode))for(var f in d.Df)throw new x.Af(55);nb(d)}delete a.parent.Df[a.name];b.Df[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.Df[b];a.ctime=a.mtime=Date.now()},rmdir(a,
b){var c=mb(a,b),d;for(d in c.Df)throw new x.Af(55);delete a.Df[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.Df)]},symlink(a,b,c){a=y.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new x.Af(28);return a.link}},Cf:{read(a,b,c,d,f){var h=a.node.Df;if(f>=a.node.If)return 0;a=Math.min(a.node.If-f,d);if(8<a&&h.subarray)b.set(h.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=h[f+d];return a},write(a,b,c,d,f,h){b.buffer===g.buffer&&(h=
!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.Df||a.Df.subarray)){if(h)return a.Df=b.subarray(c,c+d),a.If=d;if(0===a.If&&0===f)return a.Df=b.slice(c,c+d),a.If=d;if(f+d<=a.If)return a.Df.set(b.subarray(c,c+d),f),d}h=f+d;var k=a.Df?a.Df.length:0;k>=h||(h=Math.max(h,k*(1048576>k?2:1.125)>>>0),0!=k&&(h=Math.max(h,256)),k=a.Df,a.Df=new Uint8Array(h),0<a.If&&a.Df.set(k.subarray(0,a.If),0));if(a.Df.subarray&&b.subarray)a.Df.set(b.subarray(c,c+d),f);else for(h=0;h<d;h++)a.Df[f+
h]=b[c+h];a.If=Math.max(a.If,f+d);return d},Jf(a,b,c){1===c?b+=a.position:2===c&&x.isFile(a.node.mode)&&(b+=a.node.If);if(0>b)throw new x.Af(28);return b},Yf(a,b,c,d,f){if(!x.isFile(a.node.mode))throw new x.Af(43);a=a.node.Df;if(f&2||!a||a.buffer!==g.buffer){d=!0;f=lb(b);if(!f)throw new x.Af(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);g.set(a,f)}}else d=!1,f=a.byteOffset;return{zf:f,wg:d}},ag(a,b,c,d){y.Cf.write(a,b,0,d,c,!1);return 0}}},ob=
(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},pb=async a=>{a=await ha(a);return new Uint8Array(a)},qb=0,rb=null,sb=()=>{qb--;e.monitorRunDependencies?.(qb);if(0==qb&&rb){var a=rb;rb=null;a()}},tb=()=>{qb++;e.monitorRunDependencies?.(qb)},ub=[],vb=async(a,b)=>{"undefined"!=typeof Browser&&Browser.dg();for(var c of ub)if(c.canHandle(b))return c.handle(a,b);return a},xb=async(a,b,c,d,f,h,k,m)=>{var u=b?Za(Sa(a+"/"+b)):a,t=`cp ${u}`;tb(t);try{var C=c;"string"==typeof c&&(C=await pb(c));C=await vb(C,
u);m?.();h||wb(a,b,C,d,f,k)}finally{sb(t)}};function gb(a,b){x.zg[a]={Cf:b}}function z(a){return 16384===(a&61440)}function mb(a,b){var c=z(a.mode)?(c=yb(a,"x"))?c:a.Bf.lookup?0:2:54;if(c)throw new x.Af(c);for(c=x.Of[zb(a.id,b)];c;c=c.Zf){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return x.lookup(a,b)}function nb(a){var b=zb(a.parent.id,a.name);if(x.Of[b]===a)x.Of[b]=a.Zf;else for(b=x.Of[b];b;){if(b.Zf===a){b.Zf=a.Zf;break}b=b.Zf}}
function wb(a,b,c,d,f,h){var k=b;a&&(a="string"==typeof a?a:Ab(a),k=b?Sa(a+"/"+b):a);a=ob(d,f);k=x.create(k,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(f=c.length;d<f;++d)b[d]=c.charCodeAt(d);c=b}x.chmod(k,a|146);b=x.open(k,577);x.write(b,c,0,c.length,0,h);x.close(b);x.chmod(k,a)}}
function A(a,b={}){if(!a)throw new x.Af(44);b.cg??(b.cg=!0);"/"===a.charAt(0)||(a=x.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(m=>!!m);for(var d=x.root,f="/",h=0;h<a.length;h++){var k=h===a.length-1;if(k&&b.parent)break;if("."!==a[h])if(".."===a[h])if(f=Ta(f),x.pg(d)){a=f+"/"+a.slice(h+1).join("/");c--;continue a}else d=d.parent;else{f=Sa(f+"/"+a[h]);try{d=mb(d,a[h])}catch(m){if(44===m?.Hf&&k&&b.qh)return{path:f};throw m;}!d.Mf||k&&!b.cg||(d=d.Mf.root);if(40960===(d.mode&61440)&&
(!k||b.Kf)){if(!d.Bf.readlink)throw new x.Af(52);d=d.Bf.readlink(d);"/"===d.charAt(0)||(d=Ta(f)+"/"+d);a=d+"/"+a.slice(h+1).join("/");continue a}}}return{path:f,node:d}}throw new x.Af(32);}function Ab(a){for(var b;;){if(x.pg(a))return a=a.Gf.Dg,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function zb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%x.Of.length}function Bb(a){var b=zb(a.parent.id,a.name);a.Zf=x.Of[b];x.Of[b]=a}
function Cb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function yb(a,b){if(x.Cg)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Db(a,b){if(!z(a.mode))return 54;try{return mb(a,b),20}catch(c){}return yb(a,"wx")}
function Eb(a,b,c){try{var d=mb(a,b)}catch(f){return f.Hf}if(a=yb(a,"wx"))return a;if(c){if(!z(d.mode))return 54;if(x.pg(d)||Ab(d)===x.cwd())return 10}else if(z(d.mode))return 31;return 0}function Fb(a,b){if(!a)throw new x.Af(b);return a}function B(a){a=x.Pg(a);if(!a)throw new x.Af(8);return a}function Gb(a,b=-1){a=Object.assign(new x.Ig,a);if(-1==b)a:{for(b=0;b<=x.Kg;b++)if(!x.streams[b])break a;throw new x.Af(33);}a.fd=b;return x.streams[b]=a}
function Hb(a,b=-1){a=Gb(a,b);a.Cf?.Dh?.(a);return a}function Ib(a,b,c){var d=a?.Cf.Nf;a=d?a:b;d??=b.Bf.Nf;Fb(d,63);d(a,c)}function Jb(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.bg)}return b}function Kb(a){var b={vh:4096,Gh:4096,blocks:1E6,uh:5E5,th:5E5,files:x.rg,Eh:x.rg-1,Hh:42,flags:2,Mh:255};a.Bf.Fg&&Object.assign(b,a.Bf.Fg(a.Gf.rh.root));return b}function Lb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return x.Rf(a,b|8192,c)}
function Mb(a,b,c,d){Ib(a,b,{mode:c&4095|b.mode&-4096,ctime:Date.now(),Ag:d})}function Nb(a,b,c){if(z(b.mode))throw new x.Af(31);if(!x.isFile(b.mode))throw new x.Af(28);var d=yb(b,"w");if(d)throw new x.Af(d);Ib(a,b,{size:c,timestamp:Date.now()})}function Ob(a,b){a="string"==typeof a?a:Ab(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Sa(a+"/"+c);try{x.mkdir(d)}catch(f){if(20!=f.Hf)throw f;}a=d}}return d}
function Pb(a,b,c,d){a="string"==typeof a?a:Ab(a);b=Sa(a+"/"+b);return x.create(b,ob(c,d))}function Qb(a){if(!(a.oh||a.ph||a.link||a.Df))if("undefined"!=typeof XMLHttpRequest)r("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.Df=ia(a.url)}catch(b){throw new x.Af(29);}}
function Rb(a,b,c,d,f){function h(q,K,X,Y,W){q=q.node.Df;if(W>=q.length)return 0;Y=Math.min(q.length-W,Y);if(q.slice)for(var U=0;U<Y;U++)K[X+U]=q[W+U];else for(U=0;U<Y;U++)K[X+U]=q.get(W+U);return Y}class k{gg=!1;Tf=[];fg=void 0;ug=0;tg=0;get(q){if(!(q>this.length-1||0>q)){var K=q%this.chunkSize;return this.fg(q/this.chunkSize|0)[K]}}Jg(q){this.fg=q}vg(){var q=new XMLHttpRequest;q.open("HEAD",c,!1);q.send(null);200<=q.status&&300>q.status||304===q.status||r("Couldn't load "+c+". Status: "+q.status);
var K=Number(q.getResponseHeader("Content-length")),X,Y=(X=q.getResponseHeader("Accept-Ranges"))&&"bytes"===X;q=(X=q.getResponseHeader("Content-Encoding"))&&"gzip"===X;var W=1048576;Y||(W=K);var U=this;U.Jg(Na=>{var Xa=Na*W,Oa=(Na+1)*W-1;Oa=Math.min(Oa,K-1);if("undefined"==typeof U.Tf[Na]){var li=U.Tf;Xa>Oa&&r("invalid range ("+Xa+", "+Oa+") or no bytes requested!");Oa>K-1&&r("only "+K+" bytes available! programmer error!");var Z=new XMLHttpRequest;Z.open("GET",c,!1);K!==W&&Z.setRequestHeader("Range",
"bytes="+Xa+"-"+Oa);Z.responseType="arraybuffer";Z.overrideMimeType&&Z.overrideMimeType("text/plain; charset=x-user-defined");Z.send(null);200<=Z.status&&300>Z.status||304===Z.status||r("Couldn't load "+c+". Status: "+Z.status);Xa=void 0!==Z.response?new Uint8Array(Z.response||[]):db(Z.responseText||"",!0);li[Na]=Xa}"undefined"==typeof U.Tf[Na]&&r("doXHR failed!");return U.Tf[Na]});if(q||!K)W=K=1,W=K=this.fg(0).length,ka("LazyFiles on gzip forces download of the whole file when length is accessed");
this.ug=K;this.tg=W;this.gg=!0}get length(){this.gg||this.vg();return this.ug}get chunkSize(){this.gg||this.vg();return this.tg}}if("undefined"!=typeof XMLHttpRequest){ba||r("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");var m=new k;var u=void 0}else u=c,m=void 0;var t=Pb(a,b,d,f);m?t.Df=m:u&&(t.Df=null,t.url=u);Object.defineProperties(t,{If:{get:function(){return this.Df.length}}});var C={};Object.keys(t.Cf).forEach(q=>{var K=
t.Cf[q];C[q]=(...X)=>{Qb(t);return K(...X)}});C.read=(q,K,X,Y,W)=>{Qb(t);return h(q,K,X,Y,W)};C.Yf=(q,K,X)=>{Qb(t);var Y=lb(K);if(!Y)throw new x.Af(48);h(q,g,Y,K,X);return{zf:Y,wg:!0}};t.Cf=C;return t}
var x={root:null,bg:[],zg:{},streams:[],rg:1,Of:null,yg:"/",ng:!1,Cg:!0,Ng:null,eg:0,Eg:{},Af:class{name="ErrnoError";constructor(a){this.Hf=a}},Ig:class{Tf={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.Tf.flags}set flags(a){this.Tf.flags=a}get position(){return this.Tf.position}set position(a){this.Tf.position=a}},Hg:class{Bf={};Cf={};Mf=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Gf=a.Gf;this.id=x.rg++;this.name=b;this.mode=c;this.rdev=d;
this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get ph(){return z(this.mode)}get oh(){return 8192===(this.mode&61440)}},createNode(a,b,c,d){a=new x.Hg(a,b,c,d);Bb(a);return a},pg(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isFIFO(a){return 4096===(a&61440)},isSocket(a){return 49152===(a&49152)},Kg:4096,Pg:a=>x.streams[a],
Lg:{open(a){a.Cf=x.Og(a.node.rdev).Cf;a.Cf.open?.(a)},Jf(){throw new x.Af(70);}},qg:a=>a>>8,Kh:a=>a&255,Xf:(a,b)=>a<<8|b,Og:a=>x.zg[a],Gg(a,b){function c(k){x.eg--;return b(k)}function d(k){if(k){if(!d.Mg)return d.Mg=!0,c(k)}else++h>=f.length&&c(null)}"function"==typeof a&&(b=a,a=!1);x.eg++;1<x.eg&&la(`warning: ${x.eg} FS.syncfs operations in flight at once, probably just doing extra work`);var f=Jb(x.root.Gf),h=0;f.forEach(k=>{if(!k.type.Gg)return d(null);k.type.Gg(k,a,d)})},Gf(a,b,c){var d="/"===
c;if(d&&x.root)throw new x.Af(10);if(!d&&c){var f=A(c,{cg:!1});c=f.path;f=f.node;if(f.Mf)throw new x.Af(10);if(!z(f.mode))throw new x.Af(54);}b={type:a,rh:b,Dg:c,bg:[]};a=a.Gf(b);a.Gf=b;b.root=a;d?x.root=a:f&&(f.Mf=b,f.Gf&&f.Gf.bg.push(b));return a},Qh(a){a=A(a,{cg:!1});if(!a.node.Mf)throw new x.Af(28);a=a.node;var b=a.Mf,c=Jb(b);Object.keys(x.Of).forEach(d=>{for(d=x.Of[d];d;){var f=d.Zf;c.includes(d.Gf)&&nb(d);d=f}});a.Mf=null;a.Gf.bg.splice(a.Gf.bg.indexOf(b),1)},lookup(a,b){return a.Bf.lookup(a,
b)},Rf(a,b,c){var d=A(a,{parent:!0}).node;a=Ua(a);if(!a)throw new x.Af(28);if("."===a||".."===a)throw new x.Af(20);var f=Db(d,a);if(f)throw new x.Af(f);if(!d.Bf.Rf)throw new x.Af(63);return d.Bf.Rf(d,a,b,c)},Fg(a){return Kb(A(a,{Kf:!0}).node)},Ph(a){return Kb(a.node)},create(a,b=438){return x.Rf(a,b&4095|32768,0)},mkdir(a,b=511){return x.Rf(a,b&1023|16384,0)},Lh(a,b){var c=a.split("/"),d="",f;for(f of c)if(f){if(d||"/"===a.charAt(0))d+="/";d+=f;try{x.mkdir(d,b)}catch(h){if(20!=h.Hf)throw h;}}},symlink(a,
b){if(!Za(a))throw new x.Af(44);var c=A(b,{parent:!0}).node;if(!c)throw new x.Af(44);b=Ua(b);var d=Db(c,b);if(d)throw new x.Af(d);if(!c.Bf.symlink)throw new x.Af(63);return c.Bf.symlink(c,b,a)},rename(a,b){var c=Ta(a),d=Ta(b),f=Ua(a),h=Ua(b);var k=A(a,{parent:!0});var m=k.node;k=A(b,{parent:!0});k=k.node;if(!m||!k)throw new x.Af(44);if(m.Gf!==k.Gf)throw new x.Af(75);var u=mb(m,f);a=$a(a,d);if("."!==a.charAt(0))throw new x.Af(28);a=$a(b,c);if("."!==a.charAt(0))throw new x.Af(55);try{var t=mb(k,h)}catch(C){}if(u!==
t){b=z(u.mode);if(f=Eb(m,f,b))throw new x.Af(f);if(f=t?Eb(k,h,b):Db(k,h))throw new x.Af(f);if(!m.Bf.rename)throw new x.Af(63);if(u.Mf||t&&t.Mf)throw new x.Af(10);if(k!==m&&(f=yb(m,"w")))throw new x.Af(f);nb(u);try{m.Bf.rename(u,k,h),u.parent=k}catch(C){throw C;}finally{Bb(u)}}},rmdir(a){var b=A(a,{parent:!0}).node;a=Ua(a);var c=mb(b,a),d=Eb(b,a,!0);if(d)throw new x.Af(d);if(!b.Bf.rmdir)throw new x.Af(63);if(c.Mf)throw new x.Af(10);b.Bf.rmdir(b,a);nb(c)},readdir(a){a=A(a,{Kf:!0}).node;return Fb(a.Bf.readdir,
54)(a)},unlink(a){var b=A(a,{parent:!0}).node;if(!b)throw new x.Af(44);a=Ua(a);var c=mb(b,a),d=Eb(b,a,!1);if(d)throw new x.Af(d);if(!b.Bf.unlink)throw new x.Af(63);if(c.Mf)throw new x.Af(10);b.Bf.unlink(b,a);nb(c)},readlink(a){a=A(a).node;if(!a)throw new x.Af(44);if(!a.Bf.readlink)throw new x.Af(28);return a.Bf.readlink(a)},stat(a,b){a=A(a,{Kf:!b}).node;return Fb(a.Bf.Lf,63)(a)},fstat(a){var b=B(a);a=b.node;var c=b.Cf.Lf;b=c?b:a;c??=a.Bf.Lf;Fb(c,63);return c(b)},lstat(a){return x.stat(a,!0)},chmod(a,
b,c){a="string"==typeof a?A(a,{Kf:!c}).node:a;Mb(null,a,b,c)},lchmod(a,b){x.chmod(a,b,!0)},fchmod(a,b){a=B(a);Mb(a,a.node,b,!1)},chown(a,b,c,d){a="string"==typeof a?A(a,{Kf:!d}).node:a;Ib(null,a,{timestamp:Date.now(),Ag:d})},lchown(a,b,c){x.chown(a,b,c,!0)},fchown(a){a=B(a);Ib(a,a.node,{timestamp:Date.now(),Ag:!1})},truncate(a,b){if(0>b)throw new x.Af(28);a="string"==typeof a?A(a,{Kf:!0}).node:a;Nb(null,a,b)},Ih(a,b){a=B(a);if(0>b||0===(a.flags&2097155))throw new x.Af(28);Nb(a,a.node,b)},Rh(a,b,c){a=
A(a,{Kf:!0}).node;Fb(a.Bf.Nf,63)(a,{atime:b,mtime:c})},open(a,b,c=438){if(""===a)throw new x.Af(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var f=a.endsWith("/");a=A(a,{Kf:!(b&131072),qh:!0});d=a.node;a=a.path}var h=!1;if(b&64)if(d){if(b&128)throw new x.Af(20);}else{if(f)throw new x.Af(31);d=x.Rf(a,c|511,0);h=!0}if(!d)throw new x.Af(44);
8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!z(d.mode))throw new x.Af(54);if(!h&&(f=d?40960===(d.mode&61440)?32:z(d.mode)&&("r"!==Cb(b)||b&576)?31:yb(d,Cb(b)):44))throw new x.Af(f);b&512&&!h&&x.truncate(d,0);b&=-131713;f=Gb({node:d,path:Ab(d),flags:b,seekable:!0,position:0,Cf:d.Cf,sh:[],error:!1});f.Cf.open&&f.Cf.open(f);h&&x.chmod(d,c&511);!e.logReadFiles||b&1||a in x.Eg||(x.Eg[a]=1);return f},close(a){if(null===a.fd)throw new x.Af(8);a.mg&&(a.mg=null);try{a.Cf.close&&a.Cf.close(a)}catch(b){throw b;
}finally{x.streams[a.fd]=null}a.fd=null},Jf(a,b,c){if(null===a.fd)throw new x.Af(8);if(!a.seekable||!a.Cf.Jf)throw new x.Af(70);if(0!=c&&1!=c&&2!=c)throw new x.Af(28);a.position=a.Cf.Jf(a,b,c);a.sh=[];return a.position},read(a,b,c,d,f){if(0>d||0>f)throw new x.Af(28);if(null===a.fd)throw new x.Af(8);if(1===(a.flags&2097155))throw new x.Af(8);if(z(a.node.mode))throw new x.Af(31);if(!a.Cf.read)throw new x.Af(28);var h="undefined"!=typeof f;if(!h)f=a.position;else if(!a.seekable)throw new x.Af(70);b=
a.Cf.read(a,b,c,d,f);h||(a.position+=b);return b},write(a,b,c,d,f,h){if(0>d||0>f)throw new x.Af(28);if(null===a.fd)throw new x.Af(8);if(0===(a.flags&2097155))throw new x.Af(8);if(z(a.node.mode))throw new x.Af(31);if(!a.Cf.write)throw new x.Af(28);a.seekable&&a.flags&1024&&x.Jf(a,0,2);var k="undefined"!=typeof f;if(!k)f=a.position;else if(!a.seekable)throw new x.Af(70);b=a.Cf.write(a,b,c,d,f,h);k||(a.position+=b);return b},Yf(a,b,c,d,f){if(0!==(d&2)&&0===(f&2)&&2!==(a.flags&2097155))throw new x.Af(2);
if(1===(a.flags&2097155))throw new x.Af(2);if(!a.Cf.Yf)throw new x.Af(43);if(!b)throw new x.Af(28);return a.Cf.Yf(a,b,c,d,f)},ag(a,b,c,d,f){return a.Cf.ag?a.Cf.ag(a,b,c,d,f):0},og(a,b,c){if(!a.Cf.og)throw new x.Af(59);return a.Cf.og(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&r(`Invalid encoding type "${b.encoding}"`);var c=x.open(a,b.flags);a=x.stat(a).size;var d=new Uint8Array(a);x.read(c,d,0,a,0);"utf8"===b.encoding&&(d=
v(d));x.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags||577;a=x.open(a,c.flags,c.mode);"string"==typeof b&&(b=new Uint8Array(db(b,!0)));ArrayBuffer.isView(b)?x.write(a,b,0,b.byteLength,void 0,c.Bh):r("Unsupported data type");x.close(a)},cwd:()=>x.yg,chdir(a){a=A(a,{Kf:!0});if(null===a.node)throw new x.Af(44);if(!z(a.node.mode))throw new x.Af(54);var b=yb(a.node,"x");if(b)throw new x.Af(b);x.yg=a.path},dg(a,b,c){x.ng=!0;a??=e.stdin;b??=e.stdout;c??=e.stderr;a?x.Uf("/dev","stdin",a):x.symlink("/dev/tty",
"/dev/stdin");b?x.Uf("/dev","stdout",null,b):x.symlink("/dev/tty","/dev/stdout");c?x.Uf("/dev","stderr",null,c):x.symlink("/dev/tty1","/dev/stderr");x.open("/dev/stdin",0);x.open("/dev/stdout",1);x.open("/dev/stderr",1)},Oh(){x.ng=!1;for(var a of x.streams)a&&x.close(a)},Fh(a,b){try{var c=A(a,{Kf:!b});a=c.path}catch(h){}var d=!1,f=null;try{c=A(a,{parent:!0}),Ua(a),c=A(a,{Kf:!b}),d=!0,f=c.node}catch(h){}return d?f:null},Uf(a,b,c,d){a=Va("string"==typeof a?a:Ab(a),b);b=ob(!!c,!!d);var f;(f=x.Uf).qg??
(f.qg=64);f=x.Xf(x.Uf.qg++,0);gb(f,{open(h){h.seekable=!1},close(){d?.buffer?.length&&d(10)},read(h,k,m,u){for(var t=0,C=0;C<u;C++){try{var q=c()}catch(K){throw new x.Af(29);}if(void 0===q&&0===t)throw new x.Af(6);if(null===q||void 0===q)break;t++;k[m+C]=q}t&&(h.node.atime=Date.now());return t},write(h,k,m,u){for(var t=0;t<u;t++)try{d(k[m+t])}catch(C){throw new x.Af(29);}u&&(h.node.mtime=h.node.ctime=Date.now());return t}});return Lb(a,b,f)}};
function Sb(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?x.cwd():B(a).path;if(0==b.length){if(!c)throw new x.Af(44);return a}return a+"/"+b}
function Tb(a,b){p[a>>2]=b.dev;p[a+4>>2]=b.mode;p[a+8>>2]=b.nlink;p[a+12>>2]=b.uid;p[a+16>>2]=b.gid;p[a+20>>2]=b.rdev;ua[a+24>>3]=BigInt(b.size);n[a+32>>2]=4096;n[a+36>>2]=b.blocks;var c=b.atime.getTime(),d=b.mtime.getTime(),f=b.ctime.getTime();ua[a+40>>3]=BigInt(Math.floor(c/1E3));p[a+48>>2]=c%1E3*1E6;ua[a+56>>3]=BigInt(Math.floor(d/1E3));p[a+64>>2]=d%1E3*1E6;ua[a+72>>3]=BigInt(Math.floor(f/1E3));p[a+80>>2]=f%1E3*1E6;ua[a+88>>3]=BigInt(b.ino);return 0}
var Pa=void 0,Ub=a=>0===a%4&&(0!==a%100||0===a%400),Vb=[0,31,60,91,121,152,182,213,244,274,305,335],Wb=[0,31,59,90,120,151,181,212,243,273,304,334],Xb=[],Yb={},$b=()=>{if(!Zb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Yb)void 0===Yb[b]?delete a[b]:a[b]=Yb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Zb=c}return Zb},Zb,ac=[],bc,cc=a=>{var b=
ac[a];b||(ac[a]=b=bc.get(a));return b};x.Ch=(a,b,c,d,f,h,k,m,u,t)=>{xb(a,b,c,d,f,m,u,t).then(h).catch(k)};x.Nh=xb;x.Of=Array(4096);x.Gf(y,{},"/");x.mkdir("/tmp");x.mkdir("/home");x.mkdir("/home/web_user");
(function(){x.mkdir("/dev");gb(x.Xf(1,3),{read:()=>0,write:(d,f,h,k)=>k,Jf:()=>0});Lb("/dev/null",x.Xf(1,3));fb(x.Xf(5,0),ib);fb(x.Xf(6,0),jb);Lb("/dev/tty",x.Xf(5,0));Lb("/dev/tty1",x.Xf(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Ya(a),b=a.byteLength);return a[--b]};x.Uf("/dev","random",c);x.Uf("/dev","urandom",c);x.mkdir("/dev/shm");x.mkdir("/dev/shm/tmp")})();
(function(){x.mkdir("/proc");var a=x.mkdir("/proc/self");x.mkdir("/proc/self/fd");x.Gf({Gf(){var b=x.createNode(a,"fd",16895,73);b.Cf={Jf:y.Cf.Jf};b.Bf={lookup(c,d){c=+d;var f=B(c);c={parent:null,Gf:{Dg:"fake"},Bf:{readlink:()=>f.path},id:c+1};return c.parent=c},readdir(){return Array.from(x.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();x.Ng={MEMFS:y};e.noExitRuntime&&(Ha=e.noExitRuntime);e.preloadPlugins&&(ub=e.preloadPlugins);e.print&&(ka=e.print);
e.printErr&&(la=e.printErr);e.wasmBinary&&(ma=e.wasmBinary);e.thisProgram&&(da=e.thisProgram);if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();e.addRunDependency=tb;e.removeRunDependency=sb;e.setValue=Ia;e.getValue=Ga;e.FS_preloadFile=xb;e.FS_unlink=(...a)=>x.unlink(...a);e.FS_createPath=(...a)=>Ob(...a);e.FS_createDevice=(...a)=>x.Uf(...a);e.FS=x;e.FS_createDataFile=(...a)=>wb(...a);e.FS_createLazyFile=(...a)=>Rb(...a);
var dc={617692:a=>{e.TesseractProgress&&e.TesseractProgress(a)},617761:a=>{e.TesseractProgress&&e.TesseractProgress(a)},617830:a=>{e.TesseractProgress&&e.TesseractProgress(a)}},ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,jd,kd,ld,md,nd,od,pd,qd,rd,sd,td,ud,vd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,
he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,Ue,Ve,We,Xe,Ye,Ze,$e,af,bf,cf,df,ef,ff,gf,hf,jf,kf,lf,mf,nf,of,pf,qf,rf,sf,tf,uf,vf,wf,xf,yf,zf,Af,Bf,Cf,Df,Ef,Ff,Gf,Hf,If,Jf,Kf,Lf,Mf,Nf,Of,Pf,Qf,Rf,Sf,Tf,Uf,Vf,Wf,Xf,Yf,Zf,$f,ag,bg,cg,dg,eg,fg,gg,hg,ig,jg,kg,lg,mg,ng,og,pg,qg,rg,sg,tg,ug,vg,wg,xg,yg,zg,Ag,Bg,Cg,Dg,Eg,Fg,Gg,Hg,Ig,Jg,Kg,Lg,Mg,Ng,Og,Pg,Qg,Rg,Sg,Tg,Ug,Vg,Wg,Xg,Yg,Zg,$g,ah,bh,ch,dh,eh,fh,gh,hh,ih,jh,kh,lh,mh,nh,oh,ph,
qh,rh,sh,th,uh,vh,wh,xh,yh,zh,Ah,Bh,Ch,Dh,Eh,Fh,Gh,Hh,Ih,kb,Jh,Kh,Lh,Xh={a:(a,b,c,d)=>r(`Assertion failed: ${a?v(l,a):""}, at: `+[b?b?v(l,b):"":"unknown filename",c,d?d?v(l,d):"":"unknown function"]),l:(a,b,c)=>{(new Ka(a)).dg(b,c);La=a;Ma++;throw La;},r:function(a,b,c){Pa=c;try{var d=B(a);switch(b){case 0:var f=Qa();if(0>f)break;for(;x.streams[f];)f++;return Hb(d,f).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return f=Qa(),d.flags|=f,0;case 12:return f=Qa(),ra[f+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(h){if("undefined"==
typeof x||"ErrnoError"!==h.name)throw h;return-h.Hf}},J:function(a,b){try{return Tb(b,x.fstat(a))}catch(c){if("undefined"==typeof x||"ErrnoError"!==c.name)throw c;return-c.Hf}},H:function(a,b){try{if(0===b)return-28;var c=x.cwd(),d=bb(c)+1;if(b<d)return-68;cb(c,l,a,b);return d}catch(f){if("undefined"==typeof x||"ErrnoError"!==f.name)throw f;return-f.Hf}},N:function(a,b,c){Pa=c;try{var d=B(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Sf.lh){a=[3,28,127,21,4,0,
1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var f=Qa();n[f>>2]=25856;n[f+4>>2]=5;n[f+8>>2]=191;n[f+12>>2]=35387;for(var h=0;32>h;h++)g[f+h+17]=a[h]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Sf.mh)for(f=Qa(),a=[],h=0;32>h;h++)a.push(g[f+h+17]);return 0;case 21519:if(!d.tty)return-59;f=Qa();return n[f>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:return f=Qa(),x.og(d,b,f);case 21523:if(!d.tty)return-59;
d.tty.Sf.nh&&(h=[24,80],f=Qa(),ra[f>>1]=h[0],ra[f+2>>1]=h[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(k){if("undefined"==typeof x||"ErrnoError"!==k.name)throw k;return-k.Hf}},I:function(a,b,c,d){try{b=b?v(l,b):"";var f=d&256;b=Sb(a,b,d&4096);return Tb(c,f?x.lstat(b):x.stat(b))}catch(h){if("undefined"==typeof x||"ErrnoError"!==h.name)throw h;return-h.Hf}},p:function(a,b,c,d){Pa=d;try{b=b?v(l,b):"";b=Sb(a,b);var f=d?Qa():0;return x.open(b,c,f).fd}catch(h){if("undefined"==
typeof x||"ErrnoError"!==h.name)throw h;return-h.Hf}},w:function(a){try{return a=a?v(l,a):"",x.rmdir(a),0}catch(b){if("undefined"==typeof x||"ErrnoError"!==b.name)throw b;return-b.Hf}},x:function(a,b,c){try{b=b?v(l,b):"";b=Sb(a,b);if(c)if(512===c)x.rmdir(b);else return-28;else x.unlink(b);return 0}catch(d){if("undefined"==typeof x||"ErrnoError"!==d.name)throw d;return-d.Hf}},M:()=>r(""),O:a=>{do{var b=p[a>>2];a+=4;var c=p[a>>2];a+=4;var d=p[a>>2];a+=4;b=b?v(l,b):"";Ob("/",Ta(b));wb(b,null,g.subarray(d,
d+c),!0,!0,!0)}while(p[a>>2])},u:()=>{throw Infinity;},A:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);n[b>>2]=a.getUTCSeconds();n[b+4>>2]=a.getUTCMinutes();n[b+8>>2]=a.getUTCHours();n[b+12>>2]=a.getUTCDate();n[b+16>>2]=a.getUTCMonth();n[b+20>>2]=a.getUTCFullYear()-1900;n[b+24>>2]=a.getUTCDay();n[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0},B:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);
n[b>>2]=a.getSeconds();n[b+4>>2]=a.getMinutes();n[b+8>>2]=a.getHours();n[b+12>>2]=a.getDate();n[b+16>>2]=a.getMonth();n[b+20>>2]=a.getFullYear()-1900;n[b+24>>2]=a.getDay();n[b+28>>2]=(Ub(a.getFullYear())?Vb:Wb)[a.getMonth()]+a.getDate()-1|0;n[b+36>>2]=-(60*a.getTimezoneOffset());var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset(),d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();n[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},C:function(a){var b=new Date(n[a+20>>2]+1900,n[a+16>>
2],n[a+12>>2],n[a+8>>2],n[a+4>>2],n[a>>2],0),c=n[a+32>>2],d=b.getTimezoneOffset(),f=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),h=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),k=Math.min(h,f);0>c?n[a+32>>2]=Number(f!=h&&k==d):0<c!=(k==d)&&(f=Math.max(h,f),b.setTime(b.getTime()+6E4*((0<c?k:f)-d)));n[a+24>>2]=b.getDay();n[a+28>>2]=(Ub(b.getFullYear())?Vb:Wb)[b.getMonth()]+b.getDate()-1|0;n[a>>2]=b.getSeconds();n[a+4>>2]=b.getMinutes();n[a+8>>2]=b.getHours();n[a+12>>2]=b.getDate();n[a+
16>>2]=b.getMonth();n[a+20>>2]=b.getYear();a=b.getTime();return BigInt(isNaN(a)?-1:a/1E3)},y:function(a,b,c,d,f,h,k){f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var m=B(d),u=x.Yf(m,a,f,b,c),t=u.zf;n[h>>2]=u.wg;p[k>>2]=t;return 0}catch(C){if("undefined"==typeof x||"ErrnoError"!==C.name)throw C;return-C.Hf}},z:function(a,b,c,d,f,h){h=-9007199254740992>h||9007199254740992<h?NaN:Number(h);try{var k=B(f);if(c&2){c=h;if(!x.isFile(k.node.mode))throw new x.Af(43);if(!(d&2)){var m=l.slice(a,
a+b);x.ag(k,m,c,b,d)}}}catch(u){if("undefined"==typeof x||"ErrnoError"!==u.name)throw u;return-u.Hf}},D:(a,b,c,d)=>{var f=(new Date).getFullYear(),h=(new Date(f,0,1)).getTimezoneOffset();f=(new Date(f,6,1)).getTimezoneOffset();p[a>>2]=60*Math.max(h,f);n[b>>2]=Number(h!=f);b=k=>{var m=Math.abs(k);return`UTC${0<=k?"-":"+"}${String(Math.floor(m/60)).padStart(2,"0")}${String(m%60).padStart(2,"0")}`};a=b(h);b=b(f);f<h?(cb(a,l,c,17),cb(b,l,d,17)):(cb(a,l,d,17),cb(b,l,c,17))},L:function(a,b,c){if(!(0<=a&&
3>=a))return 28;ua[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},o:(a,b,c)=>{Xb.length=0;for(var d;d=l[b++];){var f=105!=d;f&=112!=d;c+=f&&c%8?4:0;Xb.push(112==d?p[c>>2]:106==d?ua[c>>3]:105==d?n[c>>2]:ta[c>>3]);c+=f?8:4}return dc[a](...Xb)},K:()=>Date.now(),v:a=>{var b=l.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-qa.buffer.byteLength+65535)/65536|
0;try{qa.grow(d);wa();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},F:(a,b)=>{var c=0,d=0,f;for(f of $b()){var h=b+c;p[a+d>>2]=h;c+=cb(f,l,h,Infinity)+1;d+=4}return 0},G:(a,b)=>{var c=$b();p[a>>2]=c.length;a=0;for(var d of c)a+=bb(d)+1;p[b>>2]=a;return 0},k:a=>{Ha||(e.onExit?.(a),na=!0);ea(a,new Ba(a))},n:function(a){try{var b=B(a);x.close(b);return 0}catch(c){if("undefined"==typeof x||"ErrnoError"!==c.name)throw c;return c.Hf}},q:function(a,b,c,d){try{a:{var f=B(a);a=b;for(var h,k=b=
0;k<c;k++){var m=p[a>>2],u=p[a+4>>2];a+=8;var t=x.read(f,g,m,u,h);if(0>t){var C=-1;break a}b+=t;if(t<u)break;"undefined"!=typeof h&&(h+=t)}C=b}p[d>>2]=C;return 0}catch(q){if("undefined"==typeof x||"ErrnoError"!==q.name)throw q;return q.Hf}},E:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var f=B(a);x.Jf(f,b,c);ua[d>>3]=BigInt(f.position);f.mg&&0===b&&0===c&&(f.mg=null);return 0}catch(h){if("undefined"==typeof x||"ErrnoError"!==h.name)throw h;return h.Hf}},
m:function(a,b,c,d){try{a:{var f=B(a);a=b;for(var h,k=b=0;k<c;k++){var m=p[a>>2],u=p[a+4>>2];a+=8;var t=x.write(f,g,m,u,h);if(0>t){var C=-1;break a}b+=t;if(t<u)break;"undefined"!=typeof h&&(h+=t)}C=b}p[d>>2]=C;return 0}catch(q){if("undefined"==typeof x||"ErrnoError"!==q.name)throw q;return q.Hf}},c:Mh,e:Nh,b:Oh,h:Ph,i:Qh,d:Rh,f:Sh,g:Th,j:Uh,s:Vh,t:Wh};function Oh(a,b,c,d){var f=Lh();try{return cc(a)(b,c,d)}catch(h){Kh(f);if(h!==h+0)throw h;Jh(1,0)}}
function Rh(a,b){var c=Lh();try{cc(a)(b)}catch(d){Kh(c);if(d!==d+0)throw d;Jh(1,0)}}function Mh(a,b){var c=Lh();try{return cc(a)(b)}catch(d){Kh(c);if(d!==d+0)throw d;Jh(1,0)}}function Th(a,b,c,d){var f=Lh();try{cc(a)(b,c,d)}catch(h){Kh(f);if(h!==h+0)throw h;Jh(1,0)}}function Sh(a,b,c){var d=Lh();try{cc(a)(b,c)}catch(f){Kh(d);if(f!==f+0)throw f;Jh(1,0)}}function Nh(a,b,c){var d=Lh();try{return cc(a)(b,c)}catch(f){Kh(d);if(f!==f+0)throw f;Jh(1,0)}}
function Ph(a,b,c,d,f){var h=Lh();try{return cc(a)(b,c,d,f)}catch(k){Kh(h);if(k!==k+0)throw k;Jh(1,0)}}function Uh(a,b,c,d,f){var h=Lh();try{cc(a)(b,c,d,f)}catch(k){Kh(h);if(k!==k+0)throw k;Jh(1,0)}}function Qh(a,b,c,d,f,h){var k=Lh();try{return cc(a)(b,c,d,f,h)}catch(m){Kh(k);if(m!==m+0)throw m;Jh(1,0)}}function Wh(a,b,c,d,f,h,k,m,u,t){var C=Lh();try{cc(a)(b,c,d,f,h,k,m,u,t)}catch(q){Kh(C);if(q!==q+0)throw q;Jh(1,0)}}
function Vh(a,b,c,d,f,h){var k=Lh();try{cc(a)(b,c,d,f,h)}catch(m){Kh(k);if(m!==m+0)throw m;Jh(1,0)}}
function Yh(){function a(){e.calledRun=!0;if(!na){va=!0;e.noFSInit||x.ng||x.dg();Zh.Q();x.Cg=!1;oa?.(e);e.onRuntimeInitialized?.();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();Da.push(b)}Ca(Da)}}if(0<qb)rb=Yh;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Fa();Ca(Ea);0<qb?rb=Yh:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);a()},1)):a()}}var Zh;
Zh=await (async function(){function a(c){Zh=c.exports;qa=Zh.P;wa();bc=Zh.$;c=Zh;e._emscripten_bind_ParagraphJustification___destroy___0=ec=c.R;e._emscripten_bind_BoolPtr___destroy___0=fc=c.S;e._emscripten_bind_TessResultRenderer_BeginDocument_1=gc=c.T;e._emscripten_bind_TessResultRenderer_AddImage_1=hc=c.U;e._emscripten_bind_TessResultRenderer_EndDocument_0=ic=c.V;e._emscripten_bind_TessResultRenderer_happy_0=jc=c.W;e._emscripten_bind_TessResultRenderer_file_extension_0=kc=c.X;e._emscripten_bind_TessResultRenderer_title_0=
lc=c.Y;e._emscripten_bind_TessResultRenderer_imagenum_0=mc=c.Z;e._emscripten_bind_TessResultRenderer___destroy___0=nc=c._;e._emscripten_bind_LongStarPtr___destroy___0=oc=c.aa;e._emscripten_bind_VoidPtr___destroy___0=pc=c.ba;e._emscripten_bind_ResultIterator_ResultIterator_1=qc=c.ca;e._emscripten_bind_ResultIterator_Begin_0=rc=c.da;e._emscripten_bind_ResultIterator_RestartParagraph_0=sc=c.ea;e._emscripten_bind_ResultIterator_IsWithinFirstTextlineOfParagraph_0=tc=c.fa;e._emscripten_bind_ResultIterator_RestartRow_0=
uc=c.ga;e._emscripten_bind_ResultIterator_Next_1=vc=c.ha;e._emscripten_bind_ResultIterator_IsAtBeginningOf_1=wc=c.ia;e._emscripten_bind_ResultIterator_IsAtFinalElement_2=xc=c.ja;e._emscripten_bind_ResultIterator_Cmp_1=yc=c.ka;e._emscripten_bind_ResultIterator_SetBoundingBoxComponents_2=zc=c.la;e._emscripten_bind_ResultIterator_BoundingBox_5=Ac=c.ma;e._emscripten_bind_ResultIterator_BoundingBox_6=Bc=c.na;e._emscripten_bind_ResultIterator_BoundingBoxInternal_5=Cc=c.oa;e._emscripten_bind_ResultIterator_Empty_1=
Dc=c.pa;e._emscripten_bind_ResultIterator_BlockType_0=Ec=c.qa;e._emscripten_bind_ResultIterator_BlockPolygon_0=Fc=c.ra;e._emscripten_bind_ResultIterator_GetBinaryImage_1=Gc=c.sa;e._emscripten_bind_ResultIterator_GetImage_5=Hc=c.ta;e._emscripten_bind_ResultIterator_Baseline_5=Ic=c.ua;e._emscripten_bind_ResultIterator_RowAttributes_3=Jc=c.va;e._emscripten_bind_ResultIterator_Orientation_4=Kc=c.wa;e._emscripten_bind_ResultIterator_ParagraphInfo_4=Lc=c.xa;e._emscripten_bind_ResultIterator_ParagraphIsLtr_0=
Mc=c.ya;e._emscripten_bind_ResultIterator_GetUTF8Text_1=Nc=c.za;e._emscripten_bind_ResultIterator_SetLineSeparator_1=Oc=c.Aa;e._emscripten_bind_ResultIterator_SetParagraphSeparator_1=Pc=c.Ba;e._emscripten_bind_ResultIterator_Confidence_1=Qc=c.Ca;e._emscripten_bind_ResultIterator_WordFontAttributes_8=Rc=c.Da;e._emscripten_bind_ResultIterator_WordRecognitionLanguage_0=Sc=c.Ea;e._emscripten_bind_ResultIterator_WordDirection_0=Tc=c.Fa;e._emscripten_bind_ResultIterator_WordIsFromDictionary_0=Uc=c.Ga;e._emscripten_bind_ResultIterator_WordIsNumeric_0=
Vc=c.Ha;e._emscripten_bind_ResultIterator_HasBlamerInfo_0=Wc=c.Ia;e._emscripten_bind_ResultIterator_HasTruthString_0=Xc=c.Ja;e._emscripten_bind_ResultIterator_EquivalentToTruth_1=Yc=c.Ka;e._emscripten_bind_ResultIterator_WordTruthUTF8Text_0=Zc=c.La;e._emscripten_bind_ResultIterator_WordNormedUTF8Text_0=$c=c.Ma;e._emscripten_bind_ResultIterator_WordLattice_1=ad=c.Na;e._emscripten_bind_ResultIterator_SymbolIsSuperscript_0=bd=c.Oa;e._emscripten_bind_ResultIterator_SymbolIsSubscript_0=cd=c.Pa;e._emscripten_bind_ResultIterator_SymbolIsDropcap_0=
dd=c.Qa;e._emscripten_bind_ResultIterator___destroy___0=ed=c.Ra;e._emscripten_bind_TextlineOrder___destroy___0=fd=c.Sa;e._emscripten_bind_ETEXT_DESC___destroy___0=gd=c.Ta;e._emscripten_bind_PageIterator_Begin_0=hd=c.Ua;e._emscripten_bind_PageIterator_RestartParagraph_0=jd=c.Va;e._emscripten_bind_PageIterator_IsWithinFirstTextlineOfParagraph_0=kd=c.Wa;e._emscripten_bind_PageIterator_RestartRow_0=ld=c.Xa;e._emscripten_bind_PageIterator_Next_1=md=c.Ya;e._emscripten_bind_PageIterator_IsAtBeginningOf_1=
nd=c.Za;e._emscripten_bind_PageIterator_IsAtFinalElement_2=od=c._a;e._emscripten_bind_PageIterator_Cmp_1=pd=c.$a;e._emscripten_bind_PageIterator_SetBoundingBoxComponents_2=qd=c.ab;e._emscripten_bind_PageIterator_BoundingBox_5=rd=c.bb;e._emscripten_bind_PageIterator_BoundingBox_6=sd=c.cb;e._emscripten_bind_PageIterator_BoundingBoxInternal_5=td=c.db;e._emscripten_bind_PageIterator_Empty_1=ud=c.eb;e._emscripten_bind_PageIterator_BlockType_0=vd=c.fb;e._emscripten_bind_PageIterator_BlockPolygon_0=wd=c.gb;
e._emscripten_bind_PageIterator_GetBinaryImage_1=xd=c.hb;e._emscripten_bind_PageIterator_GetImage_5=yd=c.ib;e._emscripten_bind_PageIterator_Baseline_5=zd=c.jb;e._emscripten_bind_PageIterator_Orientation_4=Ad=c.kb;e._emscripten_bind_PageIterator_ParagraphInfo_4=Bd=c.lb;e._emscripten_bind_PageIterator___destroy___0=Cd=c.mb;e._emscripten_bind_WritingDirection___destroy___0=Dd=c.nb;e._emscripten_bind_WordChoiceIterator_WordChoiceIterator_1=Ed=c.ob;e._emscripten_bind_WordChoiceIterator_Next_0=Fd=c.pb;
e._emscripten_bind_WordChoiceIterator_GetUTF8Text_0=Gd=c.qb;e._emscripten_bind_WordChoiceIterator_Confidence_0=Hd=c.rb;e._emscripten_bind_WordChoiceIterator___destroy___0=Id=c.sb;e._emscripten_bind_Box_get_x_0=Jd=c.tb;e._emscripten_bind_Box_get_y_0=Kd=c.ub;e._emscripten_bind_Box_get_w_0=Ld=c.vb;e._emscripten_bind_Box_get_h_0=Md=c.wb;e._emscripten_bind_Box_get_refcount_0=Nd=c.xb;e._emscripten_bind_Box___destroy___0=Od=c.yb;e._emscripten_bind_TessPDFRenderer_TessPDFRenderer_3=Pd=c.zb;e._emscripten_bind_TessPDFRenderer_BeginDocument_1=
Qd=c.Ab;e._emscripten_bind_TessPDFRenderer_AddImage_1=Rd=c.Bb;e._emscripten_bind_TessPDFRenderer_EndDocument_0=Sd=c.Cb;e._emscripten_bind_TessPDFRenderer_happy_0=Td=c.Db;e._emscripten_bind_TessPDFRenderer_file_extension_0=Ud=c.Eb;e._emscripten_bind_TessPDFRenderer_title_0=Vd=c.Fb;e._emscripten_bind_TessPDFRenderer_imagenum_0=Wd=c.Gb;e._emscripten_bind_TessPDFRenderer___destroy___0=Xd=c.Hb;e._emscripten_bind_PixaPtr___destroy___0=Yd=c.Ib;e._emscripten_bind_FloatPtr___destroy___0=Zd=c.Jb;e._emscripten_bind_ChoiceIterator_ChoiceIterator_1=
$d=c.Kb;e._emscripten_bind_ChoiceIterator_Next_0=ae=c.Lb;e._emscripten_bind_ChoiceIterator_GetUTF8Text_0=be=c.Mb;e._emscripten_bind_ChoiceIterator_Confidence_0=ce=c.Nb;e._emscripten_bind_ChoiceIterator___destroy___0=de=c.Ob;e._emscripten_bind_PixPtr___destroy___0=ee=c.Pb;e._emscripten_bind_UNICHARSET_get_script_from_script_id_1=fe=c.Qb;e._emscripten_bind_UNICHARSET_get_script_id_from_name_1=ge=c.Rb;e._emscripten_bind_UNICHARSET_get_script_table_size_0=he=c.Sb;e._emscripten_bind_UNICHARSET___destroy___0=
ie=c.Tb;e._emscripten_bind_IntPtr___destroy___0=je=c.Ub;e._emscripten_bind_Orientation___destroy___0=ke=c.Vb;e._emscripten_bind_OSBestResult_get_orientation_id_0=le=c.Wb;e._emscripten_bind_OSBestResult_get_script_id_0=me=c.Xb;e._emscripten_bind_OSBestResult_get_sconfidence_0=ne=c.Yb;e._emscripten_bind_OSBestResult_get_oconfidence_0=oe=c.Zb;e._emscripten_bind_OSBestResult___destroy___0=pe=c._b;e._emscripten_bind_Boxa_get_n_0=qe=c.$b;e._emscripten_bind_Boxa_get_nalloc_0=re=c.ac;e._emscripten_bind_Boxa_get_refcount_0=
se=c.bc;e._emscripten_bind_Boxa_get_box_0=te=c.cc;e._emscripten_bind_Boxa___destroy___0=ue=c.dc;e._emscripten_bind_PixColormap_get_array_0=ve=c.ec;e._emscripten_bind_PixColormap_get_depth_0=we=c.fc;e._emscripten_bind_PixColormap_get_nalloc_0=xe=c.gc;e._emscripten_bind_PixColormap_get_n_0=ye=c.hc;e._emscripten_bind_PixColormap___destroy___0=ze=c.ic;e._emscripten_bind_Pta_get_n_0=Ae=c.jc;e._emscripten_bind_Pta_get_nalloc_0=Be=c.kc;e._emscripten_bind_Pta_get_refcount_0=Ce=c.lc;e._emscripten_bind_Pta_get_x_0=
De=c.mc;e._emscripten_bind_Pta_get_y_0=Ee=c.nc;e._emscripten_bind_Pta___destroy___0=Fe=c.oc;e._emscripten_bind_Pix_get_w_0=Ge=c.pc;e._emscripten_bind_Pix_get_h_0=He=c.qc;e._emscripten_bind_Pix_get_d_0=Ie=c.rc;e._emscripten_bind_Pix_get_spp_0=Je=c.sc;e._emscripten_bind_Pix_get_wpl_0=Ke=c.tc;e._emscripten_bind_Pix_get_refcount_0=Le=c.uc;e._emscripten_bind_Pix_get_xres_0=Me=c.vc;e._emscripten_bind_Pix_get_yres_0=Ne=c.wc;e._emscripten_bind_Pix_get_informat_0=Oe=c.xc;e._emscripten_bind_Pix_get_special_0=
Pe=c.yc;e._emscripten_bind_Pix_get_text_0=Qe=c.zc;e._emscripten_bind_Pix_get_colormap_0=Re=c.Ac;e._emscripten_bind_Pix_get_data_0=Se=c.Bc;e._emscripten_bind_Pix___destroy___0=Te=c.Cc;e._emscripten_bind_DoublePtr___destroy___0=Ue=c.Dc;e._emscripten_bind_Dawg___destroy___0=Ve=c.Ec;e._emscripten_bind_BoxPtr___destroy___0=We=c.Fc;e._emscripten_bind_TessBaseAPI_TessBaseAPI_0=Xe=c.Gc;e._emscripten_bind_TessBaseAPI_Version_0=Ye=c.Hc;e._emscripten_bind_TessBaseAPI_SetInputName_1=Ze=c.Ic;e._emscripten_bind_TessBaseAPI_GetInputName_0=
$e=c.Jc;e._emscripten_bind_TessBaseAPI_SetInputImage_1=af=c.Kc;e._emscripten_bind_TessBaseAPI_GetInputImage_0=bf=c.Lc;e._emscripten_bind_TessBaseAPI_GetSourceYResolution_0=cf=c.Mc;e._emscripten_bind_TessBaseAPI_GetDatapath_0=df=c.Nc;e._emscripten_bind_TessBaseAPI_SetOutputName_1=ef=c.Oc;e._emscripten_bind_TessBaseAPI_SetVariable_2=ff=c.Pc;e._emscripten_bind_TessBaseAPI_SetDebugVariable_2=gf=c.Qc;e._emscripten_bind_TessBaseAPI_GetIntVariable_2=hf=c.Rc;e._emscripten_bind_TessBaseAPI_GetBoolVariable_2=
jf=c.Sc;e._emscripten_bind_TessBaseAPI_GetDoubleVariable_2=kf=c.Tc;e._emscripten_bind_TessBaseAPI_GetStringVariable_1=lf=c.Uc;e._emscripten_bind_TessBaseAPI_SaveParameters_1=mf=c.Vc;e._emscripten_bind_TessBaseAPI_RestoreParameters_1=nf=c.Wc;e._emscripten_bind_TessBaseAPI_Init_2=of=c.Xc;e._emscripten_bind_TessBaseAPI_Init_3=pf=c.Yc;e._emscripten_bind_TessBaseAPI_Init_4=qf=c.Zc;e._emscripten_bind_TessBaseAPI_GetInitLanguagesAsString_0=rf=c._c;e._emscripten_bind_TessBaseAPI_InitForAnalysePage_0=sf=c.$c;
e._emscripten_bind_TessBaseAPI_ReadConfigFile_1=tf=c.ad;e._emscripten_bind_TessBaseAPI_ReadDebugConfigFile_1=uf=c.bd;e._emscripten_bind_TessBaseAPI_SetPageSegMode_1=vf=c.cd;e._emscripten_bind_TessBaseAPI_GetPageSegMode_0=wf=c.dd;e._emscripten_bind_TessBaseAPI_TesseractRect_7=xf=c.ed;e._emscripten_bind_TessBaseAPI_ClearAdaptiveClassifier_0=yf=c.fd;e._emscripten_bind_TessBaseAPI_SetImage_1=zf=c.gd;e._emscripten_bind_TessBaseAPI_SetImage_5=Af=c.hd;e._emscripten_bind_TessBaseAPI_SetImageFile_1=Bf=c.id;
e._emscripten_bind_TessBaseAPI_SetSourceResolution_1=Cf=c.jd;e._emscripten_bind_TessBaseAPI_SetRectangle_4=Df=c.kd;e._emscripten_bind_TessBaseAPI_GetThresholdedImage_0=Ef=c.ld;e._emscripten_bind_TessBaseAPI_WriteImage_0=Ff=c.md;e._emscripten_bind_TessBaseAPI_FindLines_0=Gf=c.nd;e._emscripten_bind_TessBaseAPI_GetGradient_0=Hf=c.od;e._emscripten_bind_TessBaseAPI_GetRegions_1=If=c.pd;e._emscripten_bind_TessBaseAPI_GetTextlines_2=Jf=c.qd;e._emscripten_bind_TessBaseAPI_GetTextlines_5=Kf=c.rd;e._emscripten_bind_TessBaseAPI_GetStrips_2=
Lf=c.sd;e._emscripten_bind_TessBaseAPI_GetWords_1=Mf=c.td;e._emscripten_bind_TessBaseAPI_GetConnectedComponents_1=Nf=c.ud;e._emscripten_bind_TessBaseAPI_GetComponentImages_4=Of=c.vd;e._emscripten_bind_TessBaseAPI_GetComponentImages_7=Pf=c.wd;e._emscripten_bind_TessBaseAPI_GetThresholdedImageScaleFactor_0=Qf=c.xd;e._emscripten_bind_TessBaseAPI_AnalyseLayout_0=Rf=c.yd;e._emscripten_bind_TessBaseAPI_AnalyseLayout_1=Sf=c.zd;e._emscripten_bind_TessBaseAPI_Recognize_1=Tf=c.Ad;e._emscripten_bind_TessBaseAPI_ProcessPages_4=
Uf=c.Bd;e._emscripten_bind_TessBaseAPI_ProcessPage_6=Vf=c.Cd;e._emscripten_bind_TessBaseAPI_GetIterator_0=Wf=c.Dd;e._emscripten_bind_TessBaseAPI_GetUTF8Text_0=Xf=c.Ed;e._emscripten_bind_TessBaseAPI_GetHOCRText_1=Yf=c.Fd;e._emscripten_bind_TessBaseAPI_GetJSONText_1=Zf=c.Gd;e._emscripten_bind_TessBaseAPI_GetTSVText_1=$f=c.Hd;e._emscripten_bind_TessBaseAPI_GetBoxText_1=ag=c.Id;e._emscripten_bind_TessBaseAPI_GetUNLVText_0=bg=c.Jd;e._emscripten_bind_TessBaseAPI_GetOsdText_1=cg=c.Kd;e._emscripten_bind_TessBaseAPI_MeanTextConf_0=
dg=c.Ld;e._emscripten_bind_TessBaseAPI_AllWordConfidences_0=eg=c.Md;e._emscripten_bind_TessBaseAPI_Clear_0=fg=c.Nd;e._emscripten_bind_TessBaseAPI_End_0=gg=c.Od;e._emscripten_bind_TessBaseAPI_ClearPersistentCache_0=hg=c.Pd;e._emscripten_bind_TessBaseAPI_IsValidWord_1=ig=c.Qd;e._emscripten_bind_TessBaseAPI_IsValidCharacter_1=jg=c.Rd;e._emscripten_bind_TessBaseAPI_DetectOS_1=kg=c.Sd;e._emscripten_bind_TessBaseAPI_GetUnichar_1=lg=c.Td;e._emscripten_bind_TessBaseAPI_GetDawg_1=mg=c.Ud;e._emscripten_bind_TessBaseAPI_NumDawgs_0=
ng=c.Vd;e._emscripten_bind_TessBaseAPI_oem_0=og=c.Wd;e._emscripten_bind_TessBaseAPI___destroy___0=pg=c.Xd;e._emscripten_bind_OSResults_OSResults_0=qg=c.Yd;e._emscripten_bind_OSResults_print_scores_0=rg=c.Zd;e._emscripten_bind_OSResults_get_best_result_0=sg=c._d;e._emscripten_bind_OSResults_get_unicharset_0=tg=c.$d;e._emscripten_bind_OSResults___destroy___0=ug=c.ae;e._emscripten_bind_Pixa_get_n_0=vg=c.be;e._emscripten_bind_Pixa_get_nalloc_0=wg=c.ce;e._emscripten_bind_Pixa_get_refcount_0=xg=c.de;e._emscripten_bind_Pixa_get_pix_0=
yg=c.ee;e._emscripten_bind_Pixa_get_boxa_0=zg=c.fe;e._emscripten_bind_Pixa___destroy___0=Ag=c.ge;e._emscripten_enum_PageIteratorLevel_RIL_BLOCK=Bg=c.he;e._emscripten_enum_PageIteratorLevel_RIL_PARA=Cg=c.ie;e._emscripten_enum_PageIteratorLevel_RIL_TEXTLINE=Dg=c.je;e._emscripten_enum_PageIteratorLevel_RIL_WORD=Eg=c.ke;e._emscripten_enum_PageIteratorLevel_RIL_SYMBOL=Fg=c.le;e._emscripten_enum_OcrEngineMode_OEM_TESSERACT_ONLY=Gg=c.me;e._emscripten_enum_OcrEngineMode_OEM_LSTM_ONLY=Hg=c.ne;e._emscripten_enum_OcrEngineMode_OEM_TESSERACT_LSTM_COMBINED=
Ig=c.oe;e._emscripten_enum_OcrEngineMode_OEM_DEFAULT=Jg=c.pe;e._emscripten_enum_OcrEngineMode_OEM_COUNT=Kg=c.qe;e._emscripten_enum_WritingDirection__WRITING_DIRECTION_LEFT_TO_RIGHT=Lg=c.re;e._emscripten_enum_WritingDirection__WRITING_DIRECTION_RIGHT_TO_LEFT=Mg=c.se;e._emscripten_enum_WritingDirection__WRITING_DIRECTION_TOP_TO_BOTTOM=Ng=c.te;e._emscripten_enum_PolyBlockType_PT_UNKNOWN=Og=c.ue;e._emscripten_enum_PolyBlockType_PT_FLOWING_TEXT=Pg=c.ve;e._emscripten_enum_PolyBlockType_PT_HEADING_TEXT=
Qg=c.we;e._emscripten_enum_PolyBlockType_PT_PULLOUT_TEXT=Rg=c.xe;e._emscripten_enum_PolyBlockType_PT_EQUATION=Sg=c.ye;e._emscripten_enum_PolyBlockType_PT_INLINE_EQUATION=Tg=c.ze;e._emscripten_enum_PolyBlockType_PT_TABLE=Ug=c.Ae;e._emscripten_enum_PolyBlockType_PT_VERTICAL_TEXT=Vg=c.Be;e._emscripten_enum_PolyBlockType_PT_CAPTION_TEXT=Wg=c.Ce;e._emscripten_enum_PolyBlockType_PT_FLOWING_IMAGE=Xg=c.De;e._emscripten_enum_PolyBlockType_PT_HEADING_IMAGE=Yg=c.Ee;e._emscripten_enum_PolyBlockType_PT_PULLOUT_IMAGE=
Zg=c.Fe;e._emscripten_enum_PolyBlockType_PT_HORZ_LINE=$g=c.Ge;e._emscripten_enum_PolyBlockType_PT_VERT_LINE=ah=c.He;e._emscripten_enum_PolyBlockType_PT_NOISE=bh=c.Ie;e._emscripten_enum_PolyBlockType_PT_COUNT=ch=c.Je;e._emscripten_enum_StrongScriptDirection_DIR_NEUTRAL=dh=c.Ke;e._emscripten_enum_StrongScriptDirection_DIR_LEFT_TO_RIGHT=eh=c.Le;e._emscripten_enum_StrongScriptDirection_DIR_RIGHT_TO_LEFT=fh=c.Me;e._emscripten_enum_StrongScriptDirection_DIR_MIX=gh=c.Ne;e._emscripten_enum_ParagraphJustification__JUSTIFICATION_UNKNOWN=
hh=c.Oe;e._emscripten_enum_ParagraphJustification__JUSTIFICATION_LEFT=ih=c.Pe;e._emscripten_enum_ParagraphJustification__JUSTIFICATION_CENTER=jh=c.Qe;e._emscripten_enum_ParagraphJustification__JUSTIFICATION_RIGHT=kh=c.Re;e._emscripten_enum_TextlineOrder__TEXTLINE_ORDER_LEFT_TO_RIGHT=lh=c.Se;e._emscripten_enum_TextlineOrder__TEXTLINE_ORDER_RIGHT_TO_LEFT=mh=c.Te;e._emscripten_enum_TextlineOrder__TEXTLINE_ORDER_TOP_TO_BOTTOM=nh=c.Ue;e._emscripten_enum_Orientation__ORIENTATION_PAGE_UP=oh=c.Ve;e._emscripten_enum_Orientation__ORIENTATION_PAGE_RIGHT=
ph=c.We;e._emscripten_enum_Orientation__ORIENTATION_PAGE_DOWN=qh=c.Xe;e._emscripten_enum_Orientation__ORIENTATION_PAGE_LEFT=rh=c.Ye;e._emscripten_enum_PageSegMode_PSM_OSD_ONLY=sh=c.Ze;e._emscripten_enum_PageSegMode_PSM_AUTO_OSD=th=c._e;e._emscripten_enum_PageSegMode_PSM_AUTO_ONLY=uh=c.$e;e._emscripten_enum_PageSegMode_PSM_AUTO=vh=c.af;e._emscripten_enum_PageSegMode_PSM_SINGLE_COLUMN=wh=c.bf;e._emscripten_enum_PageSegMode_PSM_SINGLE_BLOCK_VERT_TEXT=xh=c.cf;e._emscripten_enum_PageSegMode_PSM_SINGLE_BLOCK=
yh=c.df;e._emscripten_enum_PageSegMode_PSM_SINGLE_LINE=zh=c.ef;e._emscripten_enum_PageSegMode_PSM_SINGLE_WORD=Ah=c.ff;e._emscripten_enum_PageSegMode_PSM_CIRCLE_WORD=Bh=c.gf;e._emscripten_enum_PageSegMode_PSM_SINGLE_CHAR=Ch=c.hf;e._emscripten_enum_PageSegMode_PSM_SPARSE_TEXT=Dh=c.jf;e._emscripten_enum_PageSegMode_PSM_SPARSE_TEXT_OSD=Eh=c.kf;e._emscripten_enum_PageSegMode_PSM_RAW_LINE=Fh=c.lf;e._emscripten_enum_PageSegMode_PSM_COUNT=Gh=c.mf;e._pixDestroy=c.nf;e._ptaDestroy=c.of;e._pixaDestroy=c.pf;
e._boxaDestroy=c.qf;e._pixReadMem=c.rf;e._free=Hh=c.sf;e._malloc=Ih=c.tf;e._pixReadHeaderMem=c.uf;kb=c.vf;Jh=c.wf;Kh=c.xf;Lh=c.yf;return Zh}var b={a:Xh};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});xa??=e.locateFile?e.locateFile("tesseract-core.wasm",fa):fa+"tesseract-core.wasm";return a((await Aa(b)).instance)}());Yh();function D(){}D.prototype=Object.create(D.prototype);D.prototype.constructor=D;D.prototype.Ef=D;D.Ff={};e.WrapperObject=D;
function $h(a){return(a||D).Ff}e.getCache=$h;function E(a,b){var c=$h(b),d=c[a];if(d)return d;d=Object.create((b||D).prototype);d.zf=a;return c[a]=d}e.wrapPointer=E;e.castObject=function(a,b){return E(a.zf,b)};e.NULL=E(0);e.destroy=function(a){if(!a.__destroy__)throw"Error: Cannot destroy object. (Did you create it yourself?)";a.__destroy__();delete $h(a.Ef)[a.zf]};e.compare=function(a,b){return a.zf===b.zf};e.getPointer=function(a){return a.zf};e.getClass=function(a){return a.Ef};
var ai=0,bi=0,ci=0,di=[],ei=0;function F(){if(ei){for(var a=0;a<di.length;a++)e._free(di[a]);di.length=0;e._free(ai);ai=0;bi+=ei;ei=0}ai||(bi+=128,(ai=e._malloc(bi))||r());ci=0}
function G(a){if("string"===typeof a){a=db(a);var b=g;ai||r();b=a.length*b.BYTES_PER_ELEMENT;b=b+7&-8;if(ci+b>=bi){0<b||r();ei+=b;var c=e._malloc(b);di.push(c)}else c=ai+ci,ci+=b;b=c;c=g;var d=b;switch(c.BYTES_PER_ELEMENT){case 2:d>>=1;break;case 4:d>>=2;break;case 8:d>>=3}for(var f=0;f<a.length;f++)c[d+f]=a[f];return b}return a}function fi(){throw"cannot construct a ParagraphJustification, no constructor in IDL";}fi.prototype=Object.create(D.prototype);fi.prototype.constructor=fi;
fi.prototype.Ef=fi;fi.Ff={};e.ParagraphJustification=fi;fi.prototype.__destroy__=function(){ec(this.zf)};function gi(){throw"cannot construct a BoolPtr, no constructor in IDL";}gi.prototype=Object.create(D.prototype);gi.prototype.constructor=gi;gi.prototype.Ef=gi;gi.Ff={};e.BoolPtr=gi;gi.prototype.__destroy__=function(){fc(this.zf)};function H(){throw"cannot construct a TessResultRenderer, no constructor in IDL";}H.prototype=Object.create(D.prototype);H.prototype.constructor=H;H.prototype.Ef=H;
H.Ff={};e.TessResultRenderer=H;H.prototype.BeginDocument=function(a){var b=this.zf;F();a=a&&"object"===typeof a?a.zf:G(a);return!!gc(b,a)};H.prototype.AddImage=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);return!!hc(b,a)};H.prototype.EndDocument=function(){return!!ic(this.zf)};H.prototype.happy=function(){return!!jc(this.zf)};H.prototype.file_extension=function(){return w(kc(this.zf))};H.prototype.title=H.prototype.title=function(){return w(lc(this.zf))};H.prototype.imagenum=function(){return mc(this.zf)};
H.prototype.__destroy__=function(){nc(this.zf)};function hi(){throw"cannot construct a LongStarPtr, no constructor in IDL";}hi.prototype=Object.create(D.prototype);hi.prototype.constructor=hi;hi.prototype.Ef=hi;hi.Ff={};e.LongStarPtr=hi;hi.prototype.__destroy__=function(){oc(this.zf)};function ii(){throw"cannot construct a VoidPtr, no constructor in IDL";}ii.prototype=Object.create(D.prototype);ii.prototype.constructor=ii;ii.prototype.Ef=ii;ii.Ff={};e.VoidPtr=ii;ii.prototype.__destroy__=function(){pc(this.zf)};
function I(a){a&&"object"===typeof a&&(a=a.zf);this.zf=qc(a);$h(I)[this.zf]=this}I.prototype=Object.create(D.prototype);I.prototype.constructor=I;I.prototype.Ef=I;I.Ff={};e.ResultIterator=I;I.prototype.Begin=function(){rc(this.zf)};I.prototype.RestartParagraph=function(){sc(this.zf)};I.prototype.IsWithinFirstTextlineOfParagraph=function(){return!!tc(this.zf)};I.prototype.RestartRow=function(){uc(this.zf)};I.prototype.Next=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);return!!vc(b,a)};
I.prototype.IsAtBeginningOf=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);return!!wc(b,a)};I.prototype.IsAtFinalElement=function(a,b){var c=this.zf;a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);return!!xc(c,a,b)};I.prototype.Cmp=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);return yc(b,a)};I.prototype.SetBoundingBoxComponents=function(a,b){var c=this.zf;a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);zc(c,a,b)};
I.prototype.BoundingBox=function(a,b,c,d,f,h){var k=this.zf;a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);c&&"object"===typeof c&&(c=c.zf);d&&"object"===typeof d&&(d=d.zf);f&&"object"===typeof f&&(f=f.zf);h&&"object"===typeof h&&(h=h.zf);return void 0===h?!!Ac(k,a,b,c,d,f):!!Bc(k,a,b,c,d,f,h)};
I.prototype.BoundingBoxInternal=function(a,b,c,d,f){var h=this.zf;a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);c&&"object"===typeof c&&(c=c.zf);d&&"object"===typeof d&&(d=d.zf);f&&"object"===typeof f&&(f=f.zf);return!!Cc(h,a,b,c,d,f)};I.prototype.Empty=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);return!!Dc(b,a)};I.prototype.BlockType=function(){return Ec(this.zf)};I.prototype.BlockPolygon=function(){return E(Fc(this.zf),J)};
I.prototype.GetBinaryImage=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);return E(Gc(b,a),L)};I.prototype.GetImage=function(a,b,c,d,f){var h=this.zf;a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);c&&"object"===typeof c&&(c=c.zf);d&&"object"===typeof d&&(d=d.zf);f&&"object"===typeof f&&(f=f.zf);return E(Hc(h,a,b,c,d,f),L)};
I.prototype.Baseline=function(a,b,c,d,f){var h=this.zf;a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);c&&"object"===typeof c&&(c=c.zf);d&&"object"===typeof d&&(d=d.zf);f&&"object"===typeof f&&(f=f.zf);return!!Ic(h,a,b,c,d,f)};I.prototype.RowAttributes=function(a,b,c){var d=this.zf;a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);c&&"object"===typeof c&&(c=c.zf);return!!Jc(d,a,b,c)};
I.prototype.Orientation=function(a,b,c,d){var f=this.zf;a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);c&&"object"===typeof c&&(c=c.zf);d&&"object"===typeof d&&(d=d.zf);Kc(f,a,b,c,d)};I.prototype.ParagraphInfo=function(a,b,c,d){var f=this.zf;a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);c&&"object"===typeof c&&(c=c.zf);d&&"object"===typeof d&&(d=d.zf);Lc(f,a,b,c,d)};I.prototype.ParagraphIsLtr=function(){return!!Mc(this.zf)};
I.prototype.GetUTF8Text=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);return w(Nc(b,a))};I.prototype.SetLineSeparator=function(a){var b=this.zf;F();a=a&&"object"===typeof a?a.zf:G(a);Oc(b,a)};I.prototype.SetParagraphSeparator=function(a){var b=this.zf;F();a=a&&"object"===typeof a?a.zf:G(a);Pc(b,a)};I.prototype.Confidence=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);return Qc(b,a)};
I.prototype.WordFontAttributes=function(a,b,c,d,f,h,k,m){var u=this.zf;a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);c&&"object"===typeof c&&(c=c.zf);d&&"object"===typeof d&&(d=d.zf);f&&"object"===typeof f&&(f=f.zf);h&&"object"===typeof h&&(h=h.zf);k&&"object"===typeof k&&(k=k.zf);m&&"object"===typeof m&&(m=m.zf);return w(Rc(u,a,b,c,d,f,h,k,m))};I.prototype.WordRecognitionLanguage=function(){return w(Sc(this.zf))};I.prototype.WordDirection=function(){return Tc(this.zf)};
I.prototype.WordIsFromDictionary=function(){return!!Uc(this.zf)};I.prototype.WordIsNumeric=function(){return!!Vc(this.zf)};I.prototype.HasBlamerInfo=function(){return!!Wc(this.zf)};I.prototype.HasTruthString=function(){return!!Xc(this.zf)};I.prototype.EquivalentToTruth=function(a){var b=this.zf;F();a=a&&"object"===typeof a?a.zf:G(a);return!!Yc(b,a)};I.prototype.WordTruthUTF8Text=function(){return w(Zc(this.zf))};I.prototype.WordNormedUTF8Text=function(){return w($c(this.zf))};
I.prototype.WordLattice=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);return w(ad(b,a))};I.prototype.SymbolIsSuperscript=function(){return!!bd(this.zf)};I.prototype.SymbolIsSubscript=function(){return!!cd(this.zf)};I.prototype.SymbolIsDropcap=function(){return!!dd(this.zf)};I.prototype.__destroy__=function(){ed(this.zf)};function ji(){throw"cannot construct a TextlineOrder, no constructor in IDL";}ji.prototype=Object.create(D.prototype);ji.prototype.constructor=ji;ji.prototype.Ef=ji;
ji.Ff={};e.TextlineOrder=ji;ji.prototype.__destroy__=function(){fd(this.zf)};function ki(){throw"cannot construct a ETEXT_DESC, no constructor in IDL";}ki.prototype=Object.create(D.prototype);ki.prototype.constructor=ki;ki.prototype.Ef=ki;ki.Ff={};e.ETEXT_DESC=ki;ki.prototype.__destroy__=function(){gd(this.zf)};function M(){throw"cannot construct a PageIterator, no constructor in IDL";}M.prototype=Object.create(D.prototype);M.prototype.constructor=M;M.prototype.Ef=M;M.Ff={};e.PageIterator=M;
M.prototype.Begin=function(){hd(this.zf)};M.prototype.RestartParagraph=function(){jd(this.zf)};M.prototype.IsWithinFirstTextlineOfParagraph=function(){return!!kd(this.zf)};M.prototype.RestartRow=function(){ld(this.zf)};M.prototype.Next=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);return!!md(b,a)};M.prototype.IsAtBeginningOf=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);return!!nd(b,a)};
M.prototype.IsAtFinalElement=function(a,b){var c=this.zf;a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);return!!od(c,a,b)};M.prototype.Cmp=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);return pd(b,a)};M.prototype.SetBoundingBoxComponents=function(a,b){var c=this.zf;a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);qd(c,a,b)};
M.prototype.BoundingBox=function(a,b,c,d,f,h){var k=this.zf;a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);c&&"object"===typeof c&&(c=c.zf);d&&"object"===typeof d&&(d=d.zf);f&&"object"===typeof f&&(f=f.zf);h&&"object"===typeof h&&(h=h.zf);return void 0===h?!!rd(k,a,b,c,d,f):!!sd(k,a,b,c,d,f,h)};
M.prototype.BoundingBoxInternal=function(a,b,c,d,f){var h=this.zf;a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);c&&"object"===typeof c&&(c=c.zf);d&&"object"===typeof d&&(d=d.zf);f&&"object"===typeof f&&(f=f.zf);return!!td(h,a,b,c,d,f)};M.prototype.Empty=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);return!!ud(b,a)};M.prototype.BlockType=function(){return vd(this.zf)};M.prototype.BlockPolygon=function(){return E(wd(this.zf),J)};
M.prototype.GetBinaryImage=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);return E(xd(b,a),L)};M.prototype.GetImage=function(a,b,c,d,f){var h=this.zf;a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);c&&"object"===typeof c&&(c=c.zf);d&&"object"===typeof d&&(d=d.zf);f&&"object"===typeof f&&(f=f.zf);return E(yd(h,a,b,c,d,f),L)};
M.prototype.Baseline=function(a,b,c,d,f){var h=this.zf;a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);c&&"object"===typeof c&&(c=c.zf);d&&"object"===typeof d&&(d=d.zf);f&&"object"===typeof f&&(f=f.zf);return!!zd(h,a,b,c,d,f)};M.prototype.Orientation=function(a,b,c,d){var f=this.zf;a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);c&&"object"===typeof c&&(c=c.zf);d&&"object"===typeof d&&(d=d.zf);Ad(f,a,b,c,d)};
M.prototype.ParagraphInfo=function(a,b,c,d){var f=this.zf;a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);c&&"object"===typeof c&&(c=c.zf);d&&"object"===typeof d&&(d=d.zf);Bd(f,a,b,c,d)};M.prototype.__destroy__=function(){Cd(this.zf)};function mi(){throw"cannot construct a WritingDirection, no constructor in IDL";}mi.prototype=Object.create(D.prototype);mi.prototype.constructor=mi;mi.prototype.Ef=mi;mi.Ff={};e.WritingDirection=mi;mi.prototype.__destroy__=function(){Dd(this.zf)};
function ni(a){a&&"object"===typeof a&&(a=a.zf);this.zf=Ed(a);$h(ni)[this.zf]=this}ni.prototype=Object.create(D.prototype);ni.prototype.constructor=ni;ni.prototype.Ef=ni;ni.Ff={};e.WordChoiceIterator=ni;ni.prototype.Next=function(){return!!Fd(this.zf)};ni.prototype.GetUTF8Text=function(){return w(Gd(this.zf))};ni.prototype.Confidence=function(){return Hd(this.zf)};ni.prototype.__destroy__=function(){Id(this.zf)};function N(){throw"cannot construct a Box, no constructor in IDL";}N.prototype=Object.create(D.prototype);
N.prototype.constructor=N;N.prototype.Ef=N;N.Ff={};e.Box=N;N.prototype.get_x=N.prototype.kg=function(){return Jd(this.zf)};Object.defineProperty(N.prototype,"x",{get:N.prototype.kg});N.prototype.get_y=N.prototype.lg=function(){return Kd(this.zf)};Object.defineProperty(N.prototype,"y",{get:N.prototype.lg});N.prototype.get_w=N.prototype.jg=function(){return Ld(this.zf)};Object.defineProperty(N.prototype,"w",{get:N.prototype.jg});N.prototype.get_h=N.prototype.ig=function(){return Md(this.zf)};
Object.defineProperty(N.prototype,"h",{get:N.prototype.ig});N.prototype.get_refcount=N.prototype.Qf=function(){return Nd(this.zf)};Object.defineProperty(N.prototype,"refcount",{get:N.prototype.Qf});N.prototype.__destroy__=function(){Od(this.zf)};function O(a,b,c){F();a=a&&"object"===typeof a?a.zf:G(a);b=b&&"object"===typeof b?b.zf:G(b);c&&"object"===typeof c&&(c=c.zf);this.zf=Pd(a,b,c);$h(O)[this.zf]=this}O.prototype=Object.create(D.prototype);O.prototype.constructor=O;O.prototype.Ef=O;O.Ff={};
e.TessPDFRenderer=O;O.prototype.BeginDocument=function(a){var b=this.zf;F();a=a&&"object"===typeof a?a.zf:G(a);return!!Qd(b,a)};O.prototype.AddImage=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);return!!Rd(b,a)};O.prototype.EndDocument=function(){return!!Sd(this.zf)};O.prototype.happy=function(){return!!Td(this.zf)};O.prototype.file_extension=function(){return w(Ud(this.zf))};O.prototype.title=O.prototype.title=function(){return w(Vd(this.zf))};O.prototype.imagenum=function(){return Wd(this.zf)};
O.prototype.__destroy__=function(){Xd(this.zf)};function oi(){throw"cannot construct a PixaPtr, no constructor in IDL";}oi.prototype=Object.create(D.prototype);oi.prototype.constructor=oi;oi.prototype.Ef=oi;oi.Ff={};e.PixaPtr=oi;oi.prototype.__destroy__=function(){Yd(this.zf)};function pi(){throw"cannot construct a FloatPtr, no constructor in IDL";}pi.prototype=Object.create(D.prototype);pi.prototype.constructor=pi;pi.prototype.Ef=pi;pi.Ff={};e.FloatPtr=pi;pi.prototype.__destroy__=function(){Zd(this.zf)};
function qi(a){a&&"object"===typeof a&&(a=a.zf);this.zf=$d(a);$h(qi)[this.zf]=this}qi.prototype=Object.create(D.prototype);qi.prototype.constructor=qi;qi.prototype.Ef=qi;qi.Ff={};e.ChoiceIterator=qi;qi.prototype.Next=function(){return!!ae(this.zf)};qi.prototype.GetUTF8Text=function(){return w(be(this.zf))};qi.prototype.Confidence=function(){return ce(this.zf)};qi.prototype.__destroy__=function(){de(this.zf)};function ri(){throw"cannot construct a PixPtr, no constructor in IDL";}ri.prototype=Object.create(D.prototype);
ri.prototype.constructor=ri;ri.prototype.Ef=ri;ri.Ff={};e.PixPtr=ri;ri.prototype.__destroy__=function(){ee(this.zf)};function si(){throw"cannot construct a UNICHARSET, no constructor in IDL";}si.prototype=Object.create(D.prototype);si.prototype.constructor=si;si.prototype.Ef=si;si.Ff={};e.UNICHARSET=si;si.prototype.get_script_from_script_id=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);return w(fe(b,a))};
si.prototype.get_script_id_from_name=function(a){var b=this.zf;F();a=a&&"object"===typeof a?a.zf:G(a);return ge(b,a)};si.prototype.get_script_table_size=function(){return he(this.zf)};si.prototype.__destroy__=function(){ie(this.zf)};function ti(){throw"cannot construct a IntPtr, no constructor in IDL";}ti.prototype=Object.create(D.prototype);ti.prototype.constructor=ti;ti.prototype.Ef=ti;ti.Ff={};e.IntPtr=ti;ti.prototype.__destroy__=function(){je(this.zf)};
function ui(){throw"cannot construct a Orientation, no constructor in IDL";}ui.prototype=Object.create(D.prototype);ui.prototype.constructor=ui;ui.prototype.Ef=ui;ui.Ff={};e.Orientation=ui;ui.prototype.__destroy__=function(){ke(this.zf)};function P(){throw"cannot construct a OSBestResult, no constructor in IDL";}P.prototype=Object.create(D.prototype);P.prototype.constructor=P;P.prototype.Ef=P;P.Ff={};e.OSBestResult=P;P.prototype.get_orientation_id=P.prototype.$g=function(){return le(this.zf)};
Object.defineProperty(P.prototype,"orientation_id",{get:P.prototype.$g});P.prototype.get_script_id=P.prototype.dh=function(){return me(this.zf)};Object.defineProperty(P.prototype,"script_id",{get:P.prototype.dh});P.prototype.get_sconfidence=P.prototype.bh=function(){return ne(this.zf)};Object.defineProperty(P.prototype,"sconfidence",{get:P.prototype.bh});P.prototype.get_oconfidence=P.prototype.Zg=function(){return oe(this.zf)};Object.defineProperty(P.prototype,"oconfidence",{get:P.prototype.Zg});
P.prototype.__destroy__=function(){pe(this.zf)};function Q(){throw"cannot construct a Boxa, no constructor in IDL";}Q.prototype=Object.create(D.prototype);Q.prototype.constructor=Q;Q.prototype.Ef=Q;Q.Ff={};e.Boxa=Q;Q.prototype.get_n=Q.prototype.Vf=function(){return qe(this.zf)};Object.defineProperty(Q.prototype,"n",{get:Q.prototype.Vf});Q.prototype.get_nalloc=Q.prototype.Wf=function(){return re(this.zf)};Object.defineProperty(Q.prototype,"nalloc",{get:Q.prototype.Wf});
Q.prototype.get_refcount=Q.prototype.Qf=function(){return se(this.zf)};Object.defineProperty(Q.prototype,"refcount",{get:Q.prototype.Qf});Q.prototype.get_box=Q.prototype.Sg=function(){return E(te(this.zf),vi)};Object.defineProperty(Q.prototype,"box",{get:Q.prototype.Sg});Q.prototype.__destroy__=function(){ue(this.zf)};function R(){throw"cannot construct a PixColormap, no constructor in IDL";}R.prototype=Object.create(D.prototype);R.prototype.constructor=R;R.prototype.Ef=R;R.Ff={};e.PixColormap=R;
R.prototype.get_array=R.prototype.Qg=function(){return ve(this.zf)};Object.defineProperty(R.prototype,"array",{get:R.prototype.Qg});R.prototype.get_depth=R.prototype.Xg=function(){return we(this.zf)};Object.defineProperty(R.prototype,"depth",{get:R.prototype.Xg});R.prototype.get_nalloc=R.prototype.Wf=function(){return xe(this.zf)};Object.defineProperty(R.prototype,"nalloc",{get:R.prototype.Wf});R.prototype.get_n=R.prototype.Vf=function(){return ye(this.zf)};Object.defineProperty(R.prototype,"n",{get:R.prototype.Vf});
R.prototype.__destroy__=function(){ze(this.zf)};function J(){throw"cannot construct a Pta, no constructor in IDL";}J.prototype=Object.create(D.prototype);J.prototype.constructor=J;J.prototype.Ef=J;J.Ff={};e.Pta=J;J.prototype.get_n=J.prototype.Vf=function(){return Ae(this.zf)};Object.defineProperty(J.prototype,"n",{get:J.prototype.Vf});J.prototype.get_nalloc=J.prototype.Wf=function(){return Be(this.zf)};Object.defineProperty(J.prototype,"nalloc",{get:J.prototype.Wf});
J.prototype.get_refcount=J.prototype.Qf=function(){return Ce(this.zf)};Object.defineProperty(J.prototype,"refcount",{get:J.prototype.Qf});J.prototype.get_x=J.prototype.kg=function(){return E(De(this.zf),pi)};Object.defineProperty(J.prototype,"x",{get:J.prototype.kg});J.prototype.get_y=J.prototype.lg=function(){return E(Ee(this.zf),pi)};Object.defineProperty(J.prototype,"y",{get:J.prototype.lg});J.prototype.__destroy__=function(){Fe(this.zf)};
function L(){throw"cannot construct a Pix, no constructor in IDL";}L.prototype=Object.create(D.prototype);L.prototype.constructor=L;L.prototype.Ef=L;L.Ff={};e.Pix=L;L.prototype.get_w=L.prototype.jg=function(){return Ge(this.zf)};Object.defineProperty(L.prototype,"w",{get:L.prototype.jg});L.prototype.get_h=L.prototype.ig=function(){return He(this.zf)};Object.defineProperty(L.prototype,"h",{get:L.prototype.ig});L.prototype.get_d=L.prototype.Vg=function(){return Ie(this.zf)};
Object.defineProperty(L.prototype,"d",{get:L.prototype.Vg});L.prototype.get_spp=L.prototype.fh=function(){return Je(this.zf)};Object.defineProperty(L.prototype,"spp",{get:L.prototype.fh});L.prototype.get_wpl=L.prototype.ih=function(){return Ke(this.zf)};Object.defineProperty(L.prototype,"wpl",{get:L.prototype.ih});L.prototype.get_refcount=L.prototype.Qf=function(){return Le(this.zf)};Object.defineProperty(L.prototype,"refcount",{get:L.prototype.Qf});L.prototype.get_xres=L.prototype.jh=function(){return Me(this.zf)};
Object.defineProperty(L.prototype,"xres",{get:L.prototype.jh});L.prototype.get_yres=L.prototype.kh=function(){return Ne(this.zf)};Object.defineProperty(L.prototype,"yres",{get:L.prototype.kh});L.prototype.get_informat=L.prototype.Yg=function(){return Oe(this.zf)};Object.defineProperty(L.prototype,"informat",{get:L.prototype.Yg});L.prototype.get_special=L.prototype.eh=function(){return Pe(this.zf)};Object.defineProperty(L.prototype,"special",{get:L.prototype.eh});
L.prototype.get_text=L.prototype.gh=function(){return w(Qe(this.zf))};Object.defineProperty(L.prototype,"text",{get:L.prototype.gh});L.prototype.get_colormap=L.prototype.Ug=function(){return E(Re(this.zf),R)};Object.defineProperty(L.prototype,"colormap",{get:L.prototype.Ug});L.prototype.get_data=L.prototype.Wg=function(){return Se(this.zf)};Object.defineProperty(L.prototype,"data",{get:L.prototype.Wg});L.prototype.__destroy__=function(){Te(this.zf)};
function wi(){throw"cannot construct a DoublePtr, no constructor in IDL";}wi.prototype=Object.create(D.prototype);wi.prototype.constructor=wi;wi.prototype.Ef=wi;wi.Ff={};e.DoublePtr=wi;wi.prototype.__destroy__=function(){Ue(this.zf)};function xi(){throw"cannot construct a Dawg, no constructor in IDL";}xi.prototype=Object.create(D.prototype);xi.prototype.constructor=xi;xi.prototype.Ef=xi;xi.Ff={};e.Dawg=xi;xi.prototype.__destroy__=function(){Ve(this.zf)};
function vi(){throw"cannot construct a BoxPtr, no constructor in IDL";}vi.prototype=Object.create(D.prototype);vi.prototype.constructor=vi;vi.prototype.Ef=vi;vi.Ff={};e.BoxPtr=vi;vi.prototype.__destroy__=function(){We(this.zf)};function S(){this.zf=Xe();$h(S)[this.zf]=this}S.prototype=Object.create(D.prototype);S.prototype.constructor=S;S.prototype.Ef=S;S.Ff={};e.TessBaseAPI=S;S.prototype.Version=function(){return w(Ye(this.zf))};
S.prototype.SetInputName=function(a){var b=this.zf;F();a=a&&"object"===typeof a?a.zf:G(a);Ze(b,a)};S.prototype.GetInputName=function(){return w($e(this.zf))};S.prototype.SetInputImage=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);af(b,a)};S.prototype.GetInputImage=function(){return E(bf(this.zf),L)};S.prototype.GetSourceYResolution=function(){return cf(this.zf)};S.prototype.GetDatapath=function(){return w(df(this.zf))};
S.prototype.SetOutputName=function(a){var b=this.zf;F();a=a&&"object"===typeof a?a.zf:G(a);ef(b,a)};S.prototype.SetVariable=S.prototype.SetVariable=function(a,b){var c=this.zf;F();a=a&&"object"===typeof a?a.zf:G(a);b=b&&"object"===typeof b?b.zf:G(b);return!!ff(c,a,b)};S.prototype.SetDebugVariable=function(a,b){var c=this.zf;F();a=a&&"object"===typeof a?a.zf:G(a);b=b&&"object"===typeof b?b.zf:G(b);return!!gf(c,a,b)};
S.prototype.GetIntVariable=function(a,b){var c=this.zf;F();a=a&&"object"===typeof a?a.zf:G(a);b&&"object"===typeof b&&(b=b.zf);return!!hf(c,a,b)};S.prototype.GetBoolVariable=function(a,b){var c=this.zf;F();a=a&&"object"===typeof a?a.zf:G(a);b&&"object"===typeof b&&(b=b.zf);return!!jf(c,a,b)};S.prototype.GetDoubleVariable=function(a,b){var c=this.zf;F();a=a&&"object"===typeof a?a.zf:G(a);b&&"object"===typeof b&&(b=b.zf);return!!kf(c,a,b)};
S.prototype.GetStringVariable=function(a){var b=this.zf;F();a=a&&"object"===typeof a?a.zf:G(a);return w(lf(b,a))};S.prototype.Init=function(a,b,c,d){void 0===c&&void 0!==d&&(c=3);var f=this.zf;F();a=a&&"object"===typeof a?a.zf:G(a);b=b&&"object"===typeof b?b.zf:G(b);d=d&&"object"===typeof d?d.zf:G(d);c&&"object"===typeof c&&(c=c.zf);return void 0===c&&void 0!==d?qf(f,a,b,3,d):void 0===c?of(f,a,b):void 0===d?pf(f,a,b,c):qf(f,a,b,c,d)};S.prototype.GetInitLanguagesAsString=function(){return w(rf(this.zf))};
S.prototype.InitForAnalysePage=function(){sf(this.zf)};S.prototype.SaveParameters=function(){mf(this.zf)};S.prototype.RestoreParameters=function(){nf(this.zf)};S.prototype.ReadConfigFile=function(a){var b=this.zf;F();a=a&&"object"===typeof a?a.zf:G(a);tf(b,a)};S.prototype.ReadDebugConfigFile=function(a){var b=this.zf;F();a=a&&"object"===typeof a?a.zf:G(a);uf(b,a)};S.prototype.SetPageSegMode=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);vf(b,a)};S.prototype.GetPageSegMode=function(){return wf(this.zf)};
S.prototype.TesseractRect=function(a,b,c,d,f,h,k){var m=this.zf;a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);c&&"object"===typeof c&&(c=c.zf);d&&"object"===typeof d&&(d=d.zf);f&&"object"===typeof f&&(f=f.zf);h&&"object"===typeof h&&(h=h.zf);k&&"object"===typeof k&&(k=k.zf);return w(xf(m,a,b,c,d,f,h,k))};S.prototype.ClearAdaptiveClassifier=function(){yf(this.zf)};
S.prototype.SetImage=function(a,b,c,d,f,h=1,k=0){var m=this.zf;a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);c&&"object"===typeof c&&(c=c.zf);d&&"object"===typeof d&&(d=d.zf);f&&"object"===typeof f&&(f=f.zf);void 0===b||null===b?zf(m,a,h,k):Af(m,a,b,c,d,f,h,k)};S.prototype.SetImageFile=function(a=1,b=0){return Bf(this.zf,a,b)};S.prototype.SetSourceResolution=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);Cf(b,a)};
S.prototype.SetRectangle=function(a,b,c,d){var f=this.zf;a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);c&&"object"===typeof c&&(c=c.zf);d&&"object"===typeof d&&(d=d.zf);Df(f,a,b,c,d)};S.prototype.GetThresholdedImage=function(){return E(Ef(this.zf),L)};S.prototype.WriteImage=function(a){Ff(this.zf,a)};S.prototype.GetRegions=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);return E(If(b,a),Q)};
S.prototype.GetTextlines=function(a,b,c,d,f){var h=this.zf;a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);c&&"object"===typeof c&&(c=c.zf);d&&"object"===typeof d&&(d=d.zf);f&&"object"===typeof f&&(f=f.zf);return void 0===c?E(Jf(h,a,b),Q):void 0===d?E(_emscripten_bind_TessBaseAPI_GetTextlines_3(h,a,b,c),Q):void 0===f?E(_emscripten_bind_TessBaseAPI_GetTextlines_4(h,a,b,c,d),Q):E(Kf(h,a,b,c,d,f),Q)};
S.prototype.GetStrips=function(a,b){var c=this.zf;a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);return E(Lf(c,a,b),Q)};S.prototype.GetWords=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);return E(Mf(b,a),Q)};S.prototype.GetConnectedComponents=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);return E(Nf(b,a),Q)};
S.prototype.GetComponentImages=function(a,b,c,d,f,h,k){var m=this.zf;a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);c&&"object"===typeof c&&(c=c.zf);d&&"object"===typeof d&&(d=d.zf);f&&"object"===typeof f&&(f=f.zf);h&&"object"===typeof h&&(h=h.zf);k&&"object"===typeof k&&(k=k.zf);return void 0===f?E(Of(m,a,b,c,d),Q):void 0===h?E(_emscripten_bind_TessBaseAPI_GetComponentImages_5(m,a,b,c,d,f),Q):void 0===k?E(_emscripten_bind_TessBaseAPI_GetComponentImages_6(m,a,b,c,d,f,h),Q):E(Pf(m,
a,b,c,d,f,h,k),Q)};S.prototype.GetThresholdedImageScaleFactor=function(){return Qf(this.zf)};S.prototype.AnalyseLayout=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);return void 0===a?E(Rf(b),M):E(Sf(b,a),M)};S.prototype.Recognize=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);return Tf(b,a)};S.prototype.FindLines=function(){return Gf(this.zf)};S.prototype.GetGradient=function(){return Hf(this.zf)};
S.prototype.ProcessPages=function(a,b,c,d){var f=this.zf;F();a=a&&"object"===typeof a?a.zf:G(a);b=b&&"object"===typeof b?b.zf:G(b);c&&"object"===typeof c&&(c=c.zf);d&&"object"===typeof d&&(d=d.zf);return!!Uf(f,a,b,c,d)};
S.prototype.ProcessPage=function(a,b,c,d,f,h){var k=this.zf;F();a&&"object"===typeof a&&(a=a.zf);b&&"object"===typeof b&&(b=b.zf);c=c&&"object"===typeof c?c.zf:G(c);d=d&&"object"===typeof d?d.zf:G(d);f&&"object"===typeof f&&(f=f.zf);h&&"object"===typeof h&&(h=h.zf);return!!Vf(k,a,b,c,d,f,h)};S.prototype.GetIterator=function(){return E(Wf(this.zf),I)};S.prototype.GetUTF8Text=function(){var a=Xf(this.zf),b=a?v(l,a):"";Hh(a);return b};
S.prototype.GetHOCRText=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);b=(a=Yf(b,a))?v(l,a):"";Hh(a);return b};S.prototype.GetTSVText=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);b=(a=$f(b,a))?v(l,a):"";Hh(a);return b};S.prototype.GetJSONText=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);b=(a=Zf(b,a))?v(l,a):"";Hh(a);return b};S.prototype.GetBoxText=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);b=(a=ag(b,a))?v(l,a):"";Hh(a);return b};
S.prototype.GetUNLVText=function(){var a=bg(this.zf),b=a?v(l,a):"";Hh(a);return b};S.prototype.GetOsdText=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);b=(a=cg(b,a))?v(l,a):"";Hh(a);return b};S.prototype.MeanTextConf=function(){return dg(this.zf)};S.prototype.AllWordConfidences=function(){return E(eg(this.zf),ti)};
S.prototype.AdaptToWordStr=function(a,b){var c=this.zf;F();a&&"object"===typeof a&&(a=a.zf);b=b&&"object"===typeof b?b.zf:G(b);return!!_emscripten_bind_TessBaseAPI_AdaptToWordStr_2(c,a,b)};S.prototype.Clear=function(){fg(this.zf)};S.prototype.End=function(){gg(this.zf)};S.prototype.ClearPersistentCache=function(){hg(this.zf)};S.prototype.IsValidWord=function(a){var b=this.zf;F();a=a&&"object"===typeof a?a.zf:G(a);return ig(b,a)};
S.prototype.IsValidCharacter=function(a){var b=this.zf;F();a=a&&"object"===typeof a?a.zf:G(a);return!!jg(b,a)};S.prototype.DetectOS=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);return!!kg(b,a)};S.prototype.GetUnichar=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);return w(lg(b,a))};S.prototype.GetDawg=function(a){var b=this.zf;a&&"object"===typeof a&&(a=a.zf);return E(mg(b,a),xi)};S.prototype.NumDawgs=function(){return ng(this.zf)};S.prototype.oem=function(){return og(this.zf)};
S.prototype.__destroy__=function(){pg(this.zf)};function T(){this.zf=qg();$h(T)[this.zf]=this}T.prototype=Object.create(D.prototype);T.prototype.constructor=T;T.prototype.Ef=T;T.Ff={};e.OSResults=T;T.prototype.print_scores=function(){rg(this.zf)};T.prototype.get_best_result=T.prototype.Rg=function(){return E(sg(this.zf),P)};Object.defineProperty(T.prototype,"best_result",{get:T.prototype.Rg});T.prototype.get_unicharset=T.prototype.hh=function(){return E(tg(this.zf),si)};
Object.defineProperty(T.prototype,"unicharset",{get:T.prototype.hh});T.prototype.__destroy__=function(){ug(this.zf)};function V(){throw"cannot construct a Pixa, no constructor in IDL";}V.prototype=Object.create(D.prototype);V.prototype.constructor=V;V.prototype.Ef=V;V.Ff={};e.Pixa=V;V.prototype.get_n=V.prototype.Vf=function(){return vg(this.zf)};Object.defineProperty(V.prototype,"n",{get:V.prototype.Vf});V.prototype.get_nalloc=V.prototype.Wf=function(){return wg(this.zf)};
Object.defineProperty(V.prototype,"nalloc",{get:V.prototype.Wf});V.prototype.get_refcount=V.prototype.Qf=function(){return xg(this.zf)};Object.defineProperty(V.prototype,"refcount",{get:V.prototype.Qf});V.prototype.get_pix=V.prototype.ah=function(){return E(yg(this.zf),ri)};Object.defineProperty(V.prototype,"pix",{get:V.prototype.ah});V.prototype.get_boxa=V.prototype.Tg=function(){return E(zg(this.zf),Q)};Object.defineProperty(V.prototype,"boxa",{get:V.prototype.Tg});V.prototype.__destroy__=function(){Ag(this.zf)};
(function(){function a(){e.RIL_BLOCK=Bg();e.RIL_PARA=Cg();e.RIL_TEXTLINE=Dg();e.RIL_WORD=Eg();e.RIL_SYMBOL=Fg();e.OEM_TESSERACT_ONLY=Gg();e.OEM_LSTM_ONLY=Hg();e.OEM_TESSERACT_LSTM_COMBINED=Ig();e.OEM_DEFAULT=Jg();e.OEM_COUNT=Kg();e.WRITING_DIRECTION_LEFT_TO_RIGHT=Lg();e.WRITING_DIRECTION_RIGHT_TO_LEFT=Mg();e.WRITING_DIRECTION_TOP_TO_BOTTOM=Ng();e.PT_UNKNOWN=Og();e.PT_FLOWING_TEXT=Pg();e.PT_HEADING_TEXT=Qg();e.PT_PULLOUT_TEXT=Rg();e.PT_EQUATION=Sg();e.PT_INLINE_EQUATION=Tg();e.PT_TABLE=Ug();e.PT_VERTICAL_TEXT=
Vg();e.PT_CAPTION_TEXT=Wg();e.PT_FLOWING_IMAGE=Xg();e.PT_HEADING_IMAGE=Yg();e.PT_PULLOUT_IMAGE=Zg();e.PT_HORZ_LINE=$g();e.PT_VERT_LINE=ah();e.PT_NOISE=bh();e.PT_COUNT=ch();e.DIR_NEUTRAL=dh();e.DIR_LEFT_TO_RIGHT=eh();e.DIR_RIGHT_TO_LEFT=fh();e.DIR_MIX=gh();e.JUSTIFICATION_UNKNOWN=hh();e.JUSTIFICATION_LEFT=ih();e.JUSTIFICATION_CENTER=jh();e.JUSTIFICATION_RIGHT=kh();e.TEXTLINE_ORDER_LEFT_TO_RIGHT=lh();e.TEXTLINE_ORDER_RIGHT_TO_LEFT=mh();e.TEXTLINE_ORDER_TOP_TO_BOTTOM=nh();e.ORIENTATION_PAGE_UP=oh();
e.ORIENTATION_PAGE_RIGHT=ph();e.ORIENTATION_PAGE_DOWN=qh();e.ORIENTATION_PAGE_LEFT=rh();e.PSM_OSD_ONLY=sh();e.PSM_AUTO_OSD=th();e.PSM_AUTO_ONLY=uh();e.PSM_AUTO=vh();e.PSM_SINGLE_COLUMN=wh();e.PSM_SINGLE_BLOCK_VERT_TEXT=xh();e.PSM_SINGLE_BLOCK=yh();e.PSM_SINGLE_LINE=zh();e.PSM_SINGLE_WORD=Ah();e.PSM_CIRCLE_WORD=Bh();e.PSM_SINGLE_CHAR=Ch();e.PSM_SPARSE_TEXT=Dh();e.PSM_SPARSE_TEXT_OSD=Eh();e.PSM_RAW_LINE=Fh();e.PSM_COUNT=Gh()}if(e.runtimeInitialized)a();else{var b=e.onRuntimeInitialized;e.onRuntimeInitialized=
b?function(){b.call(this);a()}:function(){a()}}})();gi.prototype.getValue=function(a){return!!Ga(this.zf+(a||0),"i8")};ti.prototype.getValue=function(a){return Ga(this.zf+4*(a||0),"i32")};pi.prototype.getValue=function(a){return Ga(this.zf+4*(a||0),"float")};wi.prototype.getValue=function(a){return Ga(this.zf+8*(a||0),"double")};vi.prototype.get=oi.prototype.get=ri.prototype.get=function(a){return Ga(this.zf+4*(a||0),"*")};function yi(){this.$f={}}
yi.prototype.wrap=function(a,b){var c=Ih(4);Ia(c,0,"i32");return this.$f[a]=E(c,b)};yi.prototype.bool=function(a){return this.wrap(a,gi)};yi.prototype.i32=function(a){return this.wrap(a,ti)};yi.prototype.f32=function(a){return this.wrap(a,pi)};yi.prototype.f64=function(a){return this.$f[a]=E(Ih(8),wi)};yi.prototype.peek=function(){var a={},b;for(b in this.$f)a[b]=this.$f[b].getValue();return a};yi.prototype.get=function(){var a={},b;for(b in this.$f)a[b]=this.$f[b].getValue(),Hh(this.$f[b].zf);return a};
I.prototype.getBoundingBox=function(a){var b=new yi;this.BoundingBox(a,b.i32("x0"),b.i32("y0"),b.i32("x1"),b.i32("y1"));return b.get()};I.prototype.getBaseline=function(a){var b=new yi;a=!!this.Baseline(a,b.i32("x0"),b.i32("y0"),b.i32("x1"),b.i32("y1"));b=b.get();b.has_baseline=a;return b};I.prototype.getRowAttributes=function(){var a=new yi;this.RowAttributes(a.f32("row_height"),a.f32("descenders"),a.f32("ascenders"));return a.get()};
I.prototype.getWordFontAttributes=function(){var a=new yi,b=this.WordFontAttributes(a.bool("is_bold"),a.bool("is_italic"),a.bool("is_underlined"),a.bool("is_monospace"),a.bool("is_serif"),a.bool("is_smallcaps"),a.i32("pointsize"),a.i32("font_id"));a=a.get();a.font_name=b;return a};e.pointerHelper=yi;va?moduleRtn=e:moduleRtn=new Promise((a,b)=>{oa=a;pa=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=TesseractCore;module.exports.default=TesseractCore}else if(typeof define==="function"&&define["amd"])define([],()=>TesseractCore);
