#!/bin/bash

set -euo pipefail
source $(dirname $0)/var.sh

LIB_PATH=third_party/leptonica
CXXFLAGS="-I$INCLUDE_DIR $OPTIM_FLAGS"
CM_FLAGS=(
  -DCMAKE_INSTALL_PREFIX=$BUILD_DIR
  -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN_FILE
  -DCMAKE_PREFIX_PATH=$BUILD_DIR
  -DGIF_LIBRARY=$LIB_DIR
  -DGIF_INCLUDE_DIR=$INCLUDE_DIR
  -DZLIB_LIBRARY=$LIB_DIR
  -DZLIB_INCLUDE_DIR=$INCLUDE_DIR
  -DPNG_LIBRARY=$LIB_DIR
  -DPNG_PNG_INCLUDE_DIR=$INCLUDE_DIR
  -DJPEG_LIBRARY=$LIB_DIR
  -DJPEG_INCLUDE_DIR=$INCLUDE_DIR
  -DTIFF_LIBRARY=$LIB_DIR
  -DTIFF_INCLUDE_DIR=$INCLUDE_DIR
  -DWEBP_LIBRARY=$LIB_DIR
  -DWEBP_INCLUDE_DIR=$INCLUDE_DIR
  -DWEBPMUX_INCLUDE_DIR=$INCLUDE_DIR
  -DHAVE_LIBJP2K=0
)
echo "CM_FLAGS=${CM_FLAGS[@]}"

cd $LIB_PATH
rm -rf build
mkdir -p build
cd build
emmake cmake .. -DCMAKE_C_FLAGS="$CXXFLAGS" ${CM_FLAGS[@]}
emmake make install -j
cd $ROOT_DIR
